---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "standardworker"
  namespace: "ztp-group"
spec:
  bindingRules:
    group: "n65"
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    #
    # configure system reserved memory
    #
    - fileName: optional/tuning/control-plane-system-reserved.yaml
      policyName: "post-install-tunning"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "4"
