---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: customcnf
  labels:
    machineconfiguration.openshift.io/role: customcnf
    pools.operator.machineconfiguration.openshift.io/customcnf: ""
spec:
  # TODO(yprokule): revise it later
  maxUnavailable: 90%
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker
          - customcnf
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/customcnf: ""
  paused: true
