---
apiVersion: v1
kind: Secret
metadata:
  name: ecore-pull-secret
  namespace: ecore
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsgInJlZ2lzdHJ5LmVjb3JlLmxhYi5lbmcudGx2Mi5yZWRoYXQuY29tOjUwMDAiOiB7ICJhdXRoIjogImIyTndMV1ZrWjJVNmIyTndMV1ZrWjJVdGNHRnpjdz09IiB9LCAicmVnaXN0cnkuZWNvcmUubGFiLmVuZy50bHYyLnJlZGhhdC5jb206NTAwNSI6IHsgImF1dGgiOiAiYjJOd0xXVmtaMlU2YjJOd0xXVmtaMlV0Y0dGemN3PT0iIH0gfX0K
