---
apiVersion: v1
kind: Secret
metadata:
  name: ecore-pull-secret
  namespace: ecore
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsgInJlZ2lzdHJ5LmVjb3JlLmxhYi5lbmcudGx2Mi5yZWRoYXQuY29tOjUwMDAiOiB7ICJhdXRoIjogImIyTndMV1ZrWjJVNmIyTndMV1ZrWjJVdGNHRnpjdz09IiB9IH0gfQo=
