---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hw-types
  namespace: ztp-site
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
data:
  ecore-cnf-isolated-cpu: "1-25,27-51,53-77,79-103"
  ecore-cnf-reserved-cpu: "0,26,52,78"
