---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hw-types
  namespace: ztp-core-policies
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
data:
  ecore-cnf-isolated-cpu: "4-25,30-51,56-77,82-103"
  ecore-cnf-reserved-cpu: "0-3,26-29,52-55,78-81"
