# Object storage credentials template
---
apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: "<access key>"
  access_key_secret: "<access key secret>"
  bucketnames: "<bucket names>"
  endpoint: "<storage endpoint>" # e.g. <https://storage.endpoint.url>
  region: "<region>"
