apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: telco-core-policies
policyDefaults:
  namespace: ztp-core-policies
  policySets: []
  placement:
    labelSelector:
      matchLabels:
        site: "ecore"
        zone: "tlv2"
  remediationAction: "inform"
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "1"
policies:
  #
  # Configure custom namespaces
  #
  - name: core-config-ns
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "3"
    manifests:
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-macvlan-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-sriov-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-nrop-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-ipvlan-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-metallb-app
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-egress-ns
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-graceful-app
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-egressip-ns-one
          labels:
            env: "sys-qa"
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-egressip-ns-two
          labels:
            env: "sys-qa"
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-metallb-segregation
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-bonded-sriov-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-rootless-dpdk-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-whereabouts

  #
  # Configure KDump on the cluster nodes
  #
  - name: configure-kdump
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "3"
    manifests:
      - path: source-crs/optional/other/kdump-master.yaml
        patches:
          - spec:
              kernelArguments:
              - crashkernel=2048M

      - path: source-crs/optional/other/kdump-worker.yaml
        patches:
          - spec:
              kernelArguments:
              - crashkernel=2048M

  #
  # Configure container-mount-namespace
  #
  - name: configure-container-ns
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "3"
    manifests:
      - path: source-crs/optional/other/mount_namespace_config_master.yaml
      - path: source-crs/optional/other/mount_namespace_config_worker.yaml


  #
  # Label nodes to be available for the assignment of egress IP addresses
  #
  - name: label-egress-ip-nodes
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "3"
    manifests:
    - path: source-crs/LabelNode.yaml
      patches:
      - metadata:
          name: openshift-worker-0.ecore.lab.eng.tlv2.redhat.com
          labels:
            k8s.ovn.org/egress-assignable: ""
    - path: source-crs/LabelNode.yaml
      patches:
      - metadata:
          name: openshift-worker-1.ecore.lab.eng.tlv2.redhat.com
          labels:
            k8s.ovn.org/egress-assignable: ""
    - path: source-crs/LabelNode.yaml
      patches:
      - metadata:
          name: openshift-worker-2.ecore.lab.eng.tlv2.redhat.com
          labels:
            k8s.ovn.org/egress-assignable: ""

  #
  # Configure custom MCPs
  #
  #- name: config-nodes-mcp
  #  policyAnnotations:
  #    ran.openshift.io/ztp-deploy-wave: "2"
  #  manifests:
  #    - path: source-crs/MachineConfigPool.yaml
  #      patches:
  #        - metadata:
  #            name: standard
  #            labels:
  #              machineconfiguration.openshift.io/role: standard
  #              pools.operator.machineconfiguration.openshift.io/standard: ""
  #          spec:
  #            machineConfigSelector:
  #              matchExpressions:
  #                - key: machineconfiguration.openshift.io/role
  #                  operator: In
  #                  values: [worker, standard]
  #            nodeSelector:
  #              matchLabels:
  #                $patch: replace
  #                node-role.kubernetes.io/standard: ""

  #    - path: source-crs/MachineConfigPool.yaml
  #      patches:
  #        - metadata:
  #            name: customcnf
  #            labels:
  #              machineconfiguration.openshift.io/role: customcnf
  #              pools.operator.machineconfiguration.openshift.io/customcnf: ""
  #          spec:
  #            machineConfigSelector:
  #              matchExpressions:
  #                - key: machineconfiguration.openshift.io/role
  #                  operator: In
  #                  values: [worker, customcnf]
  #            nodeSelector:
  #              matchLabels:
  #                $patch: replace
  #                node-role.kubernetes.io/customcnf: ""


  #
  # Configure EgressIP
  #
  - name: configure-egressip
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "8"
    manifests:
      - path: qe-source-crs/egressip/egressIP.yaml
        patches:
          - metadata:
              name: egressip-qe
              $patch: replace
            spec:
              egressIPs:
              - 10.46.187.90
              - 2620:52:0:2ebb::5a
