---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    - fileName: DefaultCatsrc.yaml
      policyName: "config-policy"
      metadata:
          name: redhat-operators-disconnected
      spec:
        displayName: Red Hat Operators Catalog
        image: registry.ecore.lab.eng.tlv2.redhat.com:5000/olm/redhat-operators:v4.14
