apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: telco-core-policies
policyDefaults:
  namespace: ztp-common
  policySets: []
  placement:
    labelSelector:
      matchExpressions:
        - key: site
          operator: In
          values:
            - "ecore"
        - key: zone
          operator: In
          values:
            - tlv2
  remediationAction: "inform"
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "1"
policies:
  #
  # Configure custom namespaces
  #
  - name: core-config-ns
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "3"
    manifests:
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-macvlan-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-sriov-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-nrop-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-ipvlan-wlkd
    - path: source-crs/customNamespace.yaml
      patches:
      - metadata:
          name: rds-metallb-app

  #
  # Configure KDump on the cluster nodes
  #
  - name: configure-kdump
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "3"
    manifests:
      - path: source-crs/optional/other/06-kdump-master.yaml
      - path: source-crs/optional/other/06-kdump-worker.yaml

  #
  # Configure container-mount-namespace
  #
  - name: configure-container-ns
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "3"
    manifests:
      - path: source-crs/optional/other/mount_namespace_config_master.yaml
      - path: source-crs/optional/other/mount_namespace_config_worker.yaml

  #
  # Configure custom MCPs
  #
  - name: config-nodes-mcp
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: 2
    manifests:
      - path: source-crs/MachineConfigPool.yaml
        patches:
          - metadata:
              name: customcnf
              labels:
                machineconfiguration.openshift.io/role: customcnf
                pools.operator.machineconfiguration.openshift.io/customcnf: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, customcnf]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/customcnf: ""
      - path: source-crs/MachineConfigPool.yaml
        patches:
          - metadata:
              name: standard
              labels:
                machineconfiguration.openshift.io/role: standard
                pools.operator.machineconfiguration.openshift.io/standard: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, standard]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/standard: ""
