---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    # routingViaHost enabled only during cluster installation?
    #- fileName: RoutingViaHost.yaml
    #  policyName: "config-network"
    - fileName: OperatorHub.yaml
      policyName: "disable-operator-hub"
    - fileName: DefaultCatsrc.yaml
      policyName: "config-policy"
      metadata:
          name: redhat-operators-disconnected
      spec:
        displayName: Red Hat Operators Catalog
        image: registry.ecore.lab.eng.tlv2.redhat.com:5000/olm/redhat-operators:v4.14
    # install and configure SR-IOV operator
    - fileName: SriovSubscriptionNS.yaml
      policyName: "sriov-operator-policy"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "sriov-operator-policy"
    - fileName: SriovSubscription.yaml
      policyName: "sriov-operator-policy"
      spec:
        channel: "4.14"
        source: redhat-operators-disconnected
        installPlanApproval: "Automatic"
    - fileName: SriovOperatorConfig.yaml
      policyName: "sriov-operator-policy-config"
      spec:
        configDaemonNodeSelector:
          node-role.kubernetes.io/ht100gb: ""
    # install and configure MetalLB operator
    - fileName: metallb/ns.yaml
      policyName: "metallb-operator-policy"
    - fileName: metallb/operatorGroup.yaml
      policyName: "metallb-operator-policy"
    - fileName: metallb/subscription.yaml
      policyName: "metallb-operator-policy"
      spec:
        channel: "stable"
        source: redhat-operators-disconnected
        installPlanApproval: "Automatic"
    - fileName: metallb/instance.yaml
      policyName: "metallb-operator-policy"
    # confgire MetalLB operator
    - fileName: metallb/bfdProfile.yaml
      policyName: "metallb-operator-policy-config"
    - fileName: metallb/bgpPeer.yaml
      policyName: "metallb-operator-policy-config"
    - fileName: metallb/community.yaml
      policyName: "metallb-operator-policy-config"
    - fileName: metallb/ipAddressPool.yaml
      policyName: "metallb-operator-policy-config"
    - fileName: metallb/bgpAdvertisement.yaml
      policyName: "metallb-operator-policy-config"
    # label HT nodes
    - fileName: LabelHTNode.yaml
      policyName: "label-node"
      metadata:
        name: openshift-worker-0.ecore.lab.eng.tlv2.redhat.com
        labels:
          node-role.kubernetes.io/standard: ''
          env: "qe"
    - fileName: LabelHTNode.yaml
      policyName: "label-node"
      metadata:
        name: openshift-worker-1.ecore.lab.eng.tlv2.redhat.com
        labels:
          node-role.kubernetes.io/standard: ''
          env: "qe"
    - fileName: LabelHTNode.yaml
      policyName: "label-node"
      metadata:
        name: openshift-worker-2.ecore.lab.eng.tlv2.redhat.com
        labels:
          node-role.kubernetes.io/ht100gb: ''
          env: "qe"
      spec:
        taints:
          - effect: NoSchedule
            key: sriov
            value: "true"
    - fileName: LabelHTNode.yaml
      policyName: "label-node"
      metadata:
        name: openshift-worker-3.ecore.lab.eng.tlv2.redhat.com
        labels:
          node-role.kubernetes.io/ht100gb: ''
          env: "qe"
      spec:
        taints:
          - effect: NoSchedule
            key: sriov
            value: "true"
    # install ODF operator
    - fileName: odf/ns.yaml
      policyName: "odf-operator"
    - fileName: odf/operatorGroup.yaml
      policyName: "odf-operator"
    - fileName: odf/subscription.yaml
      policyName: "odf-operator"
    # configure ODF operator
    - fileName: odf/external-ceph-secret.yaml
      policyName: "odf-operator-configure-1"
    - fileName: odf/odf-storage-cluster.yaml
      policyName: "odf-operator-configure-2"
    # storage classes from ODF
    - fileName: odf/odf-sc-ceph-rbd.yaml
      policyName: "odf-storage-classes"
    - fileName: odf/odf-sc-ceph-fs.yaml
      policyName: "odf-storage-classes"
    - fileName: odf/odf-sc-nooba.yaml
      policyName: "odf-storage-classes"
      metadata:
        name: openshift-storage.noobaa.io
    # install NMState operator
    - fileName: nmstate/namespace.yaml
      policyName: "nmstate-operator"
    - fileName: nmstate/operatorGroup.yaml
      policyName: "nmstate-operator"
    - fileName: nmstate/subscription.yaml
      policyName: "nmstate-operator"
    - fileName: nmstate/instance.yaml
      policyName: "nmstate-operator"
    # configure custom Namespaces
    - fileName: customNamespace.yaml
      policyName: "custom-namespaces"
      metadata:
        name: pcc
    - fileName: customNamespace.yaml
      policyName: "custom-namespaces"
      metadata:
        name: pcg
    # configure MachineConfigPools
    - fileName: MachineConfigPool.yaml
      policyName: "config-policy"
      metadata:
        name: ht100gb
        labels:
          machineconfiguration.openshift.io/role: ht100gb
          pools.operator.machineconfiguration.openshift.io/ht100gb: ""
      spec:
        maxUnavailable: 1
        machineConfigSelector:
          matchExpressions:
            - key: machineconfiguration.openshift.io/role
              operator: In
              values:
                - worker
                - ht100gb
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/ht100gb: ""
        paused: false
    - fileName: MachineConfigPool.yaml
      policyName: "config-policy"
      metadata:
        name: standard
        labels:
          machineconfiguration.openshift.io/role: standard
          pools.operator.machineconfiguration.openshift.io/standard: ""
      spec:
        maxUnavailable: "90%"
        machineConfigSelector:
          matchExpressions:
            - key: machineconfiguration.openshift.io/role
              operator: In
              values:
                - worker
                - standard
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/standard: ""
        paused: false
    # configure extra kernel modules on control-plane nodes
    - fileName: MachineConfigGeneric.yaml
      policyName: "config-policy"
      metadata:
        name: 40-load-kernel-modules-master
        labels:
          machineconfiguration.openshift.io/role: master
      spec:
        config:
          # Release info found in https://github.com/coreos/butane/releases
          ignition:
            version: 3.2.0
          storage:
            files:
            - contents:
                source: data:,
              mode: 420
              overwrite: true
              path: /etc/modprobe.d/kernel-blacklist.conf
            - contents:
                source: data:text/plain;charset=utf-8;base64,aXBfZ3JlCmlwNl90YWJsZXMKaXA2dF9SRUpFQ1QKaXA2dGFibGVfZmlsdGVyCmlwNnRhYmxlX21hbmdsZQppcHRhYmxlX2ZpbHRlcgppcHRhYmxlX21hbmdsZQppcHRhYmxlX25hdAp4dF9tdWx0aXBvcnQKeHRfb3duZXIKeHRfUkVESVJFQ1QKeHRfc3RhdGlzdGljCnh0X1RDUE1TUwp4dF91MzI=
              mode: 420
              overwrite: true
              path: /etc/modules-load.d/kernel-load.conf
    # configure extra kernel modules on worker nodes
    - fileName: MachineConfigGeneric.yaml
      policyName: "config-policy"
      metadata:
        name: 40-load-kernel-modules-worker
        labels:
          machineconfiguration.openshift.io/role: worker
      spec:
        config:
          # Release info found in https://github.com/coreos/butane/releases
          ignition:
            version: 3.2.0
          storage:
            files:
            - contents:
                source: data:,
              mode: 420
              overwrite: true
              path: /etc/modprobe.d/kernel-blacklist.conf
            - contents:
                source: data:text/plain;charset=utf-8;base64,aXBfZ3JlCmlwNl90YWJsZXMKaXA2dF9SRUpFQ1QKaXA2dGFibGVfZmlsdGVyCmlwNnRhYmxlX21hbmdsZQppcHRhYmxlX2ZpbHRlcgppcHRhYmxlX21hbmdsZQppcHRhYmxlX25hdAp4dF9tdWx0aXBvcnQKeHRfb3duZXIKeHRfUkVESVJFQ1QKeHRfc3RhdGlzdGljCnh0X1RDUE1TUwp4dF91MzI=
              mode: 420
              overwrite: true
              path: /etc/modules-load.d/kernel-load.conf
    # configure system reserved memory
    - fileName: system-reserved-memory.yaml
      policyName: "post-install-tunning"
      metadata:
        name: autosizing-master
      spec:
        autoSizingReserved: true
        machineConfigPoolSelector:
          matchLabels:
            pools.operator.machineconfiguration.openshift.io/master: ""
    - fileName: system-reserved-memory.yaml
      policyName: "post-install-tunning"
      metadata:
        name: autosizing-standard
      spec:
        autoSizingReserved: true
        machineConfigPoolSelector:
          matchLabels:
            pools.operator.machineconfiguration.openshift.io/standard: ""
    # configure MACVLAN networks
    - fileName: AddAdditionalNetworks.yaml
      policyName: "configure-macvlan"
      spec:
        additionalNetworks:
        - name: pc-mm-ext
          namespace: pcc
          rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "pc-mm-ext", "plugins": [{"type": "macvlan", "master": "bond1", "ipam": {}}] }'
          type: Raw
        - name: eric-pc-routing-engine-net0
          namespace: pcc
          rawCNIConfig: '{ "cniVersion": "0.4.0", "name": "eric-pc-routing-engine-net0", "plugins": [ {"type": "macvlan", "master": "bond1", "mode": "private" },{ "type": "tuning", "name": "tuning-arp" }] }'
          type: Raw
        - name: eric-pc-vpn-gateway-forwarder-common
          namespace: pcc
          rawCNIConfig: '{ "cniVersion": "0.4.0", "name": "eric-pc-vpn-gateway-forwarder-common", "plugins": [{"type": "macvlan", "master": "bond1", "mode": "bridge" }, { "type": "tuning", "name": "tuning-arp" }]}'
          type: Raw
        - name: eric-pc-routing-engine
          namespace: pcg
          rawCNIConfig: '{ "cniVersion": "0.4.0", "name": "eric-pc-routing-engine", "plugins": [{"type": "macvlan", "master": "bond1", "mode": "private" }, { "type": "tuning", "name": "tuning-arp" }]}'
          type: Raw
    # configure SR-IOV Network Node Policy
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-nnp"
      metadata:
        name: sriovleftdpdkmellanox
      spec:
        resourceName: "sriovleftdpdkmellanox"
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        mtu: 9000
        numVfs: 4
        nicSelector:
          # consider switching to PCI paths
          pfNames: ['ens4f0np0', 'ens5f0np0']
        deviceType: netdevice
        isRdma: True
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-nnp"
      metadata:
        name: sriovrightdpdkmellanox
      spec:
        resourceName: "sriovrightdpdkmellanox"
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        mtu: 9000
        numVfs: 4
        nicSelector:
          # consider switching to PCI paths
          pfNames: ['ens4f1np1', 'ens5f1np1']
        deviceType: netdevice
        isRdma: True
    # configure performance profile
    - fileName: PerformanceProfile.yaml
      policyName: "post-install-tunning"
      metadata:
        name: ht100gb
        annotations:
          kubeletconfig.experimental: |
            {"systemReserved": {"memory": "8Gi"}, "topologyManagerScope": "pod"}
      spec:
        cpu:
          isolated: 1-25,27-51,53-77,79-103
          reserved: 0,26,52,78
        hugepages:
          defaultHugepagesSize: 1G
          pages:
          - count: 6
            node: 0
            size: 1G
          - count: 6
            node: 1
            size: 1G
        net:
          devices:
          - interfaceName: ens4*
          - interfaceName: ens5*
          userLevelNetworking: true
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        numa:
          topologyPolicy: single-numa-node
        machineConfigPoolSelector:
          pools.operator.machineconfiguration.openshift.io/ht100gb: ""
    # configure socket buffer tunning
    - fileName: TunedPerformancePatch.yaml
      policyName: "post-install-tunning"
      metadata:
        name: pfcp-socket-size
      spec:
        profile:
        - data: |
            [main]
            summary=Description of pfcp-socket-size profile
            include=openshift-control-plane
            [sysctl]
            net.core.rmem_max=8388608
            net.core.wmem_max=8388608
            net.core.rmem_default=238860
            net.core.wmem_default=238860
            net.ipv6.conf.bond1.accept_ra=0
            net.ipv4.conf.bond0/355.forwarding=1
          name: pfcp-socket-size-master
        - data: |
            [main]
            summary=Description of pfcp-socket-size profile
            include=openshift-node
            [sysctl]
            net.core.rmem_max=8388608
            net.core.wmem_max=8388608
            net.core.rmem_default=238860
            net.core.wmem_default=238860
            net.ipv6.conf.bond1.accept_ra=0
            net.ipv4.conf.bond0/355.forwarding=1
          name: pfcp-socket-size-standard
        recommend:
        - machineConfigLabels:
            machineconfiguration.openshift.io/role: "master"
          match:
          - label: node-role.kubernetes.io/master
          priority: 10
          profile: pfcp-socket-size-master
        - machineConfigLabels:
            machineconfiguration.openshift.io/role: "standard"
          match:
          - label: node-role.kubernetes.io/standard
          priority: 20
          profile: pfcp-socket-size-standard
