---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    # routingViaHost enabled only during cluster installation?
    #- fileName: RoutingViaHost.yaml
    #  policyName: "config-network"
    - fileName: OperatorHub.yaml
      policyName: "disable-operator-hub"
    - fileName: DefaultCatsrc.yaml
      policyName: "config-policy"
      metadata:
          name: redhat-operators-disconnected
      spec:
        displayName: Red Hat Operators Catalog
        image: registry.ecore.lab.eng.tlv2.redhat.com:5000/olm/redhat-operators:v4.15
    # install and configure SR-IOV operator
    - fileName: SriovSubscriptionNS.yaml
      policyName: "sriov-operator-policy"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "sriov-operator-policy"
    - fileName: SriovSubscription.yaml
      policyName: "sriov-operator-policy"
      spec:
        channel: "stable"
        source: redhat-operators-disconnected
    - fileName: SriovOperatorConfig.yaml
      policyName: "sriov-operator-policy-config"
      spec:
        configDaemonNodeSelector:
          node-role.kubernetes.io/worker: ""
    # install and configure Logging
    - fileName: ClusterLogNS.yaml
      policyName: "cluster-logging-op"
    - fileName: ClusterLogOperGroup.yaml
      policyName: "cluster-logging-op"
    - fileName: ClusterLogSubscription.yaml
      policyName: "cluster-logging-op"
    # NOTE(yprokule): ClusterLogging instance by default uses wave 10
    - fileName: ClusterLogging.yaml
      policyName: "cluster-logging-configure"
    # install and configure MetalLB operator
    - fileName: metallb/ns.yaml
      policyName: "metallb-operator-policy"
    - fileName: metallb/operatorGroup.yaml
      policyName: "metallb-operator-policy"
    - fileName: metallb/subscription.yaml
      policyName: "metallb-operator-policy"
      spec:
        channel: "stable"
        source: redhat-operators-disconnected
        installPlanApproval: "Automatic"
    #
    # confgire MetalLB operator moved to a site folder
    #
    # configure Monitoring
    - fileName: "GenericConfigMap.yaml"
      policyName: "dedicated-service-monitor"
      metadata:
        name: cluster-monitoring-config
        namespace: openshift-monitoring
        annotations:
          ran.openshift.io/ztp-deploy-wave: "16"
      data:
        config.yaml: |
          prometheusK8s:
            dedicatedServiceMonitors:
              enabled: true
            retention: 15d
            volumeClaimTemplate:
              spec:
                storageClassName: ocs-external-storagecluster-ceph-rbd
                resources:
                  requests:
                    storage: 100Gi
          alertmanagerMain:
            volumeClaimTemplate:
              spec:
                storageClassName: ocs-external-storagecluster-ceph-rbd
                resources:
                  requests:
                    storage: 20Gi
    # install NMState operator
    - fileName: nmstate/namespace.yaml
      policyName: "nmstate-operator"
    - fileName: nmstate/operatorGroup.yaml
      policyName: "nmstate-operator"
    - fileName: nmstate/subscription.yaml
      policyName: "nmstate-operator"
    - fileName: nmstate/instance.yaml
      policyName: "nmstate-operator"
    # configure custom Namespaces
    - fileName: customNamespace.yaml
      policyName: "custom-namespaces"
      metadata:
        name: pcc
    - fileName: customNamespace.yaml
      policyName: "custom-namespaces"
      metadata:
        name: pcg
    #
    # 'standard' MCP creation moved to extra-manifests
    #
    # configure Chronyd for control-plane nodes in disconnected setup
    - fileName: MachineConfigGeneric.yaml
      policyName: "config-policy"
      metadata:
        name: 98-master-etc-chrony-conf
        labels:
          machineconfiguration.openshift.io/role: master
      spec:
        config:
          # Release info found in https://github.com/coreos/butane/releases
          ignition:
            version: 3.2.0
          storage:
            files:
            - contents:
                source: data:text/plain;charset=utf-8;base64,c2VydmVyIHJlZ2lzdHJ5LmVjb3JlLmxhYi5lbmcudGx2Mi5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgbnRwMS5udHAtMDAxLnByb2QuaWFkMi5kYy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgbnRwMi5udHAtMDAxLnByb2QuaWFkMi5kYy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2sxLmJvcy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2syLmJvcy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2suY29ycC5yZWRoYXQuY29tIGlidXJzdApzdHJhdHVtd2VpZ2h0IDAKZHJpZnRmaWxlIC92YXIvbGliL2Nocm9ueS9kcmlmdApydGNzeW5jCm1ha2VzdGVwIDEwIDMKYmluZGNtZGFkZHJlc3MgMTI3LjAuMC4xCmJpbmRjbWRhZGRyZXNzIDo6MQprZXlmaWxlIC9ldGMvY2hyb255LmtleXMKbm9jbGllbnRsb2cKbG9nY2hhbmdlIDAuNQpsb2dkaXIgL3Zhci9sb2cvY2hyb255Cg==
                verification: {}
              filesystem: root
              group:
                name: root
              mode: 420
              path: /etc/chrony.conf
              user:
                name: root
    #
    # Configuration for Rootless Pods(fromRDS)
    #
    - fileName: MachineConfigGeneric.yaml
      policyName: "rootless-pods"
      metadata:
        name: 99-worker-setsebool
        labels:
          machineconfiguration.openshift.io/role: worker
      spec:
        systemd:
          units:
            - contents: |
                [Unit]
                Description=Set SELinux boolean for tap cni plugin
                Before=kubelet.service

                [Service]
                Type=oneshot
                ExecStart=/sbin/setsebool container_use_devices=on
                RemainAfterExit=true

                [Install]
                WantedBy=multi-user.target graphical.target
              enabled: true
              name: setsebool.service
    # configure Chronyd for non control-plane nodes in disconnected setup
    - fileName: MachineConfigGeneric.yaml
      policyName: "config-policy"
      metadata:
        name: 98-worker-etc-chrony-conf
        labels:
          machineconfiguration.openshift.io/role: worker
      spec:
        config:
          # Release info found in https://github.com/coreos/butane/releases
          ignition:
            version: 3.2.0
          storage:
            files:
            - contents:
                source: data:text/plain;charset=utf-8;base64,c2VydmVyIHJlZ2lzdHJ5LmVjb3JlLmxhYi5lbmcudGx2Mi5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgbnRwMS5udHAtMDAxLnByb2QuaWFkMi5kYy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgbnRwMi5udHAtMDAxLnByb2QuaWFkMi5kYy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2sxLmJvcy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2syLmJvcy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2suY29ycC5yZWRoYXQuY29tIGlidXJzdApzdHJhdHVtd2VpZ2h0IDAKZHJpZnRmaWxlIC92YXIvbGliL2Nocm9ueS9kcmlmdApydGNzeW5jCm1ha2VzdGVwIDEwIDMKYmluZGNtZGFkZHJlc3MgMTI3LjAuMC4xCmJpbmRjbWRhZGRyZXNzIDo6MQprZXlmaWxlIC9ldGMvY2hyb255LmtleXMKbm9jbGllbnRsb2cKbG9nY2hhbmdlIDAuNQpsb2dkaXIgL3Zhci9sb2cvY2hyb255Cg==
                verification: {}
              filesystem: root
              group:
                name: root
              mode: 420
              path: /etc/chrony.conf
              user:
                name: root
    # configure extra kernel modules on control-plane nodes
    - fileName: MachineConfigGeneric.yaml
      policyName: "config-policy"
      metadata:
        name: 40-load-kernel-modules-master
        labels:
          machineconfiguration.openshift.io/role: master
      spec:
        config:
          # Release info found in https://github.com/coreos/butane/releases
          ignition:
            version: 3.2.0
          storage:
            files:
            - contents:
                source: data:,
              mode: 420
              overwrite: true
              path: /etc/modprobe.d/kernel-blacklist.conf
            - contents:
                source: data:text/plain;charset=utf-8;base64,aXBfZ3JlCmlwNl90YWJsZXMKaXA2dF9SRUpFQ1QKaXA2dGFibGVfZmlsdGVyCmlwNnRhYmxlX21hbmdsZQppcHRhYmxlX2ZpbHRlcgppcHRhYmxlX21hbmdsZQppcHRhYmxlX25hdAp4dF9tdWx0aXBvcnQKeHRfb3duZXIKeHRfUkVESVJFQ1QKeHRfc3RhdGlzdGljCnh0X1RDUE1TUwp4dF91MzI=
              mode: 420
              overwrite: true
              path: /etc/modules-load.d/kernel-load.conf
    # configure extra kernel modules on worker nodes
    - fileName: MachineConfigGeneric.yaml
      policyName: "config-policy"
      metadata:
        name: 40-load-kernel-modules-worker
        labels:
          machineconfiguration.openshift.io/role: worker
      spec:
        config:
          # Release info found in https://github.com/coreos/butane/releases
          ignition:
            version: 3.2.0
          storage:
            files:
            - contents:
                source: data:,
              mode: 420
              overwrite: true
              path: /etc/modprobe.d/kernel-blacklist.conf
            - contents:
                source: data:text/plain;charset=utf-8;base64,aXBfZ3JlCmlwNl90YWJsZXMKaXA2dF9SRUpFQ1QKaXA2dGFibGVfZmlsdGVyCmlwNnRhYmxlX21hbmdsZQppcHRhYmxlX2ZpbHRlcgppcHRhYmxlX21hbmdsZQppcHRhYmxlX25hdAp4dF9tdWx0aXBvcnQKeHRfb3duZXIKeHRfUkVESVJFQ1QKeHRfc3RhdGlzdGljCnh0X1RDUE1TUwp4dF91MzI=
              mode: 420
              overwrite: true
              path: /etc/modules-load.d/kernel-load.conf
    # configure system reserved memory
    - fileName: system-reserved-memory.yaml
      policyName: "post-install-tunning"
      metadata:
        name: autosizing-master
      spec:
        autoSizingReserved: true
        machineConfigPoolSelector:
          matchLabels:
            pools.operator.machineconfiguration.openshift.io/master: ""
    - fileName: system-reserved-memory.yaml
      policyName: "post-install-tunning"
      metadata:
        name: autosizing-standard
      spec:
        autoSizingReserved: true
        machineConfigPoolSelector:
          matchLabels:
            pools.operator.machineconfiguration.openshift.io/standard: ""
    # configure MACVLAN networks
    - fileName: AddAdditionalNetworks.yaml
      policyName: "configure-macvlan"
      spec:
        additionalNetworks:
        - name: pc-mm-ext
          namespace: pcc
          rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "pc-mm-ext", "plugins": [{"type": "macvlan", "master": "bond1", "ipam": {}}] }'
          type: Raw
        - name: eric-pc-routing-engine-net0
          namespace: pcc
          rawCNIConfig: '{ "cniVersion": "0.4.0", "name": "eric-pc-routing-engine-net0", "plugins": [ {"type": "macvlan", "master": "bond1", "mode": "private" },{ "type": "tuning", "name": "tuning-arp" }] }'
          type: Raw
        - name: eric-pc-vpn-gateway-forwarder-common
          namespace: pcc
          rawCNIConfig: '{ "cniVersion": "0.4.0", "name": "eric-pc-vpn-gateway-forwarder-common", "plugins": [{"type": "macvlan", "master": "bond1", "mode": "bridge" }, { "type": "tuning", "name": "tuning-arp" }]}'
          type: Raw
        - name: eric-pc-routing-engine
          namespace: pcg
          rawCNIConfig: '{ "cniVersion": "0.4.0", "name": "eric-pc-routing-engine", "plugins": [{"type": "macvlan", "master": "bond1", "mode": "private" }, { "type": "tuning", "name": "tuning-arp" }]}'
          type: Raw
    # configure socket buffer tunning
    - fileName: TunedPerformancePatch.yaml
      policyName: "post-install-tunning"
      metadata:
        name: pfcp-socket-size
      spec:
        profile:
        - data: |
            [main]
            summary=Description of pfcp-socket-size profile
            include=openshift-control-plane
            [sysctl]
            net.core.rmem_max=8388608
            net.core.wmem_max=8388608
            net.core.rmem_default=238860
            net.core.wmem_default=238860
            net.ipv6.conf.bond1.accept_ra=0
          name: pfcp-socket-size-master
        - data: |
            [main]
            summary=Description of pfcp-socket-size profile
            include=openshift-node
            [sysctl]
            net.core.rmem_max=8388608
            net.core.wmem_max=8388608
            net.core.rmem_default=238860
            net.core.wmem_default=238860
            net.ipv6.conf.bond1.accept_ra=0
          name: pfcp-socket-size-standard
        recommend:
        - machineConfigLabels:
            machineconfiguration.openshift.io/role: "master"
          match:
          - label: node-role.kubernetes.io/master
          priority: 10
          profile: pfcp-socket-size-master
        - machineConfigLabels:
            machineconfiguration.openshift.io/role: "standard"
          match:
          - label: node-role.kubernetes.io/standard
          priority: 20
          profile: pfcp-socket-size-standard
    #
    # TODO(YPROKULE): check if schedulable control-plane is part of RDS
    # configure schedulable masters
    #- fileName: "MastersSchedulable.yaml"
    #  policyName: "config-cluster"
