apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: telco-optimize-ztp
policyDefaults:
  namespace: ztp-group
  policySets: []
  placement:
    labelSelector:
      matchExpressions:
        - key: site
          operator: In
          values:
            - "ecore"
        - key: zone
          operator: In
          values:
            - tlv2
        - key: ztp-done
          operator: DoesNotExist
  remediationAction: "inform"
policies:
  - name: pause-cp-mcp
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "1"
    evaluationInterval:
      compliant: never
    manifests:
      - path: qe-source-crs/CustomMCP.yaml
        # This policy is evaluted only once
        # so, it does not conflict with the unpause one
        patches:
          - metadata:
              name: master
            spec:
              $patch: replace
              paused: true

  #
  # we unpause, and change the max-unavailable
  # to allow reoboting more than one node at once
  #
  - name: custom-mcp-unpause
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "11"
    evaluationInterval:
      compliant: never
    manifests:
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: master
              annotations:
                ran.openshift.io/ztp-unpause-done: ""
            spec:
              $patch: replace
              paused: false
              maxUnavailable: 1
            status:
              conditions:
              - type: Updated
                status: "True"
              - type: Updating
                status: "False"

      #- path: ../siteconfig/custom-manifests/50-mcp-st.yaml
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: standard
              annotations:
                ran.openshift.io/ztp-unpause-done: ""
            spec:
              $patch: replace
              paused: false
              maxUnavailable: 75%
            status:
              conditions:
              - type: Updated
                status: "True"
              - type: Updating
                status: "False"

      # Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `kustomize build <path to cached source>/policygentemplates --enable-alpha-plugins` failed exit status 1: 
      # Error: error processing the PolicyGenerator file '/tmp/kust-plugin-config-844016449': the manifest path ../siteconfig/custom-manifests/50-mcp-st.yaml is not in the same directory tree as the kustomization.yaml file :
      # failure in plugin configured via /tmp/kust-plugin-config-844016449; exit status 1
      #- path: ../siteconfig/custom-manifests/50-mcp-customcnf.yaml
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: customcnf
              annotations:
                ran.openshift.io/ztp-unpause-done: ""
            spec:
              $patch: replace
              paused: false
              maxUnavailable: 75%
            status:
              conditions:
              - type: Updated
                status: "True"
              - type: Updating
                status: "False"
  #
  # we set the MCP configuration to its default about maxUnavailable
  #
  - name: custom-mcp-set-maxunavailable
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "10001"
    evaluationInterval:
      compliant: never
    manifests:
      #- path: ../siteconfig/custom-manifests/50-mcp-st.yaml
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: standard
              annotations:
                ran.openshift.io/ztp-unpause-done: ""
            spec:
              maxUnavailable: 1
              $patch: replace
              paused: false

      #- path: ../siteconfig/custom-manifests/50-mcp-customcnf.yaml
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: customcnf
              annotations:
                ran.openshift.io/ztp-unpause-done: ""
            spec:
              maxUnavailable: 1
              $patch: replace
              paused: false
