apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: core-customer-policies-22
policyDefaults:
  namespace: ztp-core-policies
  policySets: []
  placement:
    labelSelector:
      matchLabels:
        site: "ecore"
        zone: "tlv2"
      # matchExpressions:
      #   - key: ztp-done
      #     operator: DoesNotExist
  remediationAction: "inform"
policies:
  # Local-only policy - pause master MCP at deployment start
  # Not in telco-reference (assumes MCPs paused via extra-manifests at install time)
  #- name: pause-cp-mcp
  #  policyAnnotations:
  #    ran.openshift.io/ztp-deploy-wave: "1"
  #  evaluationInterval:
  #    compliant: never
  #  manifests:
  #    - path: qe-source-crs/CustomMCP.yaml
  #      # This policy is evaluted only once
  #      # so, it does not conflict with the unpause one
  #      patches:
  #        - metadata:
  #            name: master
  #          spec:
  #            $patch: replace
  #            paused: true

  #
  # we unpause, and change the max-unavailable
  # to allow reoboting more than one node at once
  #
  - name: custom-mcp-unpause-22
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "200"
    evaluationInterval:
      compliant: never
    manifests:
      #
      # master MCP must be already unpaused in the cluster as it's not paused by default
      #
      #- path: qe-source-crs/CustomMCP.yaml
      #  patches:
      #    - metadata:
      #        name: master
      #      spec:
      #        #$patch: replace
      #        paused: false
      #        maxUnavailable: 1
      #      status:
      #        conditions:
      #        - type: Updated
      #          status: "True"
      #        - type: Updating
      #          status: "False"

      - path: custom-manifests/standard-mcp.yaml
        patches:
          - spec:
              #$patch: replace
              paused: false
              maxUnavailable: 100%
            status:
              conditions:
              - type: Updated
                status: "True"
              - type: Updating
                status: "False"

      - path: custom-manifests/customcnf-mcp.yaml
        patches:
          - spec:
              #$patch: replace
              paused: false
              maxUnavailable: 100%
            status:
              conditions:
              - type: Updated
                status: "True"
              - type: Updating
                status: "False"
  #
  # we set the MCP configuration to its default about maxUnavailable
  #
  - name: core-custom-mcp-set-maxavailable-22
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "201"
    #evaluationInterval:
    #  compliant: never
    manifests:
      - path: custom-manifests/standard-mcp.yaml
        patches:
          - spec:
              maxUnavailable: 1

      - path: custom-manifests/customcnf-mcp.yaml
        patches:
          - spec:
              maxUnavailable: 1
