---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: core-baseline-20
policyDefaults:
  namespace: ztp-core-policies
  policySets: []
  placement:
    labelSelector:
      matchExpressions:
        - key: site
          operator: In
          values:
            - "ecore"
        - key: zone
          operator: In
          values:
            - tlv2
        - key: version
          operator: In
          values:
            - "4.20"
  remediationAction: "inform"
policies:
  #
  # Base cluster configuration
  #
  - name: core-cluster-config-4.20
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "1"
    manifests:
      - path: source-crs/required/other/operator-hub.yaml
        # TODO(yprokule): check and update telco-core repo
        complianceType: mustonlyhave
      - path: source-crs/required/other/catalog-source.yaml
        patches:
          - metadata:
              name: redhat-operators-disconnected
            spec:
              image: registry.ecore.lab.eng.tlv2.redhat.com:5000/olm/redhat-operators:v4.20
      - path: source-crs/required/scheduling/Scheduler.yaml
        patches:
          - spec:
              mastersSchedulable: false
              # TODO(yprokule): check and update telco-core repo
              $patch: replace
              policy: null

  #
  # Core cluster OLM operators
  #
  - name: core-operator-subs-4.20
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "5"
    manifests:
      #
      # Install Cluster Logging
      #
      - path: source-crs/optional/logging/ClusterLogNS.yaml
      - path: source-crs/optional/logging/ClusterLogOperGroup.yaml
      - path: source-crs/optional/logging/ClusterLogSubscription.yaml
        patches:
          - spec:
              channel: stable-6.3
              installPlanApproval: Manual

      - path: source-crs/optional/logging/ClusterLogOperatorStatus.yaml
        patches:
        - metadata:
            $patch: replace
            annotations: null
          status:
            components:
              refs:
              - kind: ClusterServiceVersion
                namespace: openshift-logging
                # Update with specific target version
                name: cluster-logging.v6.3.1
                conditions:
                  - type: Succeeded
                    status: "True"
                    reason: InstallSucceeded
      #
      # Install SR-IOV
      #
      - path: source-crs/required/networking/sriov/SriovSubscriptionNS.yaml
      - path: source-crs/required/networking/sriov/SriovSubscriptionOperGroup.yaml
      - path: source-crs/required/networking/sriov/SriovSubscription.yaml
        patches:
          - spec:
              installPlanApproval: Manual
      #
      # Install ODF
      #
      - path: source-crs/required/storage/odf-external/odfNS.yaml
      - path: source-crs/required/storage/odf-external/odfOperGroup.yaml
      - path: source-crs/required/storage/odf-external/odfSubscription.yaml
        patches:
          - spec:
              # NOTE: production catSrc doesn't have 4.20 version but 4.19 so using it
              channel: stable-4.19
              installPlanApproval: Manual
              source: redhat-operators-disconnected
      #
      # Install MetalLB
      #
      - path: source-crs/required/networking/metallb/metallbNS.yaml
      - path: source-crs/required/networking/metallb/metallbOperGroup.yaml
      - path: source-crs/required/networking/metallb/metallbSubscription.yaml
        patches:
          - spec:
              installPlanApproval: Manual
      #
      # Install NROP
      #
      - path: source-crs/required/scheduling/NROPSubscriptionNS.yaml
      - path: source-crs/required/scheduling/NROPSubscriptionOperGroup.yaml
      - path: source-crs/required/scheduling/NROPSubscription.yaml
        patches:
          - spec:
              channel: "4.20"
              installPlanApproval: Manual
      #
      # Install NMState
      #
      - path: source-crs/required/networking/NMStateNS.yaml
      - path: source-crs/required/networking/NMStateOperGroup.yaml
      - path: source-crs/required/networking/NMStateSubscription.yaml
        patches:
          - spec:
              installPlanApproval: Manual

  #
  # Operator configuration
  #
  - name: core-operator-config-4.20
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "7"
    manifests:
      - path: source-crs/optional/logging/ClusterLogServiceAccount.yaml
      - path: source-crs/optional/logging/ClusterLogServiceAccountAuditBinding.yaml
      - path: source-crs/optional/logging/ClusterLogServiceAccountInfrastructureBinding.yaml

      - path: source-crs/required/networking/sriov/SriovOperatorConfig.yaml
        patches:
        - spec:
            # Required for mellanox plugins running with secureboot enabled.
            # Firmware MUST be pre-configured
            disablePlugins:
            - mellanox
            featureGates:
              resourceInjectorMatchCondition: true

      - path: source-crs/required/networking/NMState.yaml

      - path: source-crs/required/scheduling/sched.yaml
        patches:
        - spec:
            # Image spec should be the latest for the release
            imageSpec: "registry.ecore.lab.eng.tlv2.redhat.com:5000/nrop/noderesourcetopology-scheduler-rhel9:v4.20.0"
