---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - common-policy.yaml
  - mno-update-policy-4.14.rc.2.yml
  # configure VLAN sub-interfaces on the cluster nodes
  - sites/ecore-tlv2/configure-lb-intersite-vlan.yaml
  - sites/ecore-tlv2/configure-lb-oam-vlan.yaml
  - sites/ecore-tlv2/configure-lb-signaling-vlan.yaml
  - sites/ecore-tlv2/configure-storage-vlan.yaml
  # label nodes
  - sites/ecore-tlv2/label-nodes.yaml
  # configure HT nodes
  - sites/ecore-tlv2/config-ht-nodes.yaml
  # configure bond1 interface
  - sides/ecore-tlv2/configure-bond1.yaml
  # configure MetalLB
  - sites/ecore-tlv2/config-metallb-networks.yaml
  # configure ODF
  - sites/ecore-tlv2/deoploy-odf.yaml
  # cluster validation
  - sites/ecore-tlv2/packet-core-validator.yaml
resources:
  - policies-namespace.yaml
