---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - core-baseline.yaml
  - core-overlay.yaml
  - common-policy-generator.yaml
  - core-finish.yaml
  ## configure VLAN sub-interfaces on the cluster nodes
  - sites/ecore-tlv2/configure-lb-intersite-vlan-generator.yaml
  - sites/ecore-tlv2/configure-lb-oam-vlan-generator.yaml
  - sites/ecore-tlv2/configure-lb-signaling-vlan-generator.yaml
  - sites/ecore-tlv2/configure-storage-vlan-generator.yaml
  - sites/ecore-tlv2/configure-vlan-496.yaml
  ## cluster validation
  #- sites/ecore-tlv2/packet-core-validator-generator.yaml
  ## configure nodes
  - sites/ecore-tlv2/config-nodes-generator.yaml
  # Configure NADs
  - sites/ecore-tlv2/configure-sriov-bond-generator.yaml
resources:
  - resources/policies-namespace.yaml
  - resources/managedclusterset-bindings.yaml
  - resources/sriov-config.yaml
  - resources/hw-types.yaml
  - resources/regional.yaml
