---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: upgrade-19
policyDefaults:
  namespace: ztp-update
  policySets: []
  placement:
    labelSelector:
      matchExpressions:
        - key: site
          operator: In
          values:
            - "ecore"
        - key: zone
          operator: In
          values:
            - tlv2
        - key: upgrade-version-4-20
          operator: Exists
  remediationAction: "inform"
policies:
  #
  # Prepare for upgrade to 4.19
  #
  - name: core-upgrade-prep-19-for-20
    policyAnnotations:
      ran.openshift.io/soak-seconds: "30"
    manifests:
      #
      # Update catalogsource to point to latest versions
      #
      - path: source-crs/required/other/catalog-source.yaml
        patches:
        - metadata:
            name: redhat-operators-disconnected
            annotations:
              ran.openshift.io/ztp-deploy-wave: "1"
          spec:
            displayName: Red Hat Disconnected Operators Catalog
            image: registry.ecore.lab.eng.tlv2.redhat.com:5000/olm/redhat-operators:v4.19
            publisher: Red Hat
            sourceType: grpc
      # pause 'standard' MCP
      - path: source-crs/MachineConfigPool.yaml
        patches:
          - metadata:
              name: standard
              labels:
                $patch: replace
                machineconfiguration.openshift.io/role: standard
            spec:
              $patch: replace
              paused: true
      # pause 'customcnf' MCP
      - path: source-crs/MachineConfigPool.yaml
        patches:
          - metadata:
              name: customcnf
              labels:
                $patch: replace
                machineconfiguration.openshift.io/role: customcnf
            spec:
              $patch: replace
              paused: true
      #
      # Provide admin ack for deprecated API
      # TODO(yprokule): check if this is needed during 4.19 to 4.20 update.
      #
      #- path: source-crs/GenericConfigMap.yaml
      #  patches:
      #    - metadata:
      #        name: admin-acks
      #        namespace: openshift-config
      #      data:
      #        ack-4.15-kube-1.29-api-removals-in-4.16: "true"

  #
  # Perform cluster upgrade
  #
  - name: core-upgrade-ocp-19-to-20
    manifests:
      - path: source-crs/ClusterVersion.yaml
        patches:
        - spec:
            channel: stable-4.20
            upstream: http://registry.ecore.lab.eng.tlv2.redhat.com:8090/yp-graph
            desiredUpdate:
              version: 4.20.0-ec.5
              image: registry.ecore.lab.eng.tlv2.redhat.com:5005/openshift-release-dev/ocp-release@sha256:545fb749b1352490a35532cbfba1575fc4002910e3cf68bd011036a26d6d1d3b
              force: true
        - status:
            history:
            - version: 4.20.0-ec.5
              state: "Completed"
  #
  # Update operators
  #
  - name: upgrade-olm-19
    manifests:
      # update ODF
      - path: source-crs/required/storage/odf-external/odfSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable-4.19"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # update SR-IOV
      - path: source-crs/required/networking/sriov/SriovSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # update MetalLB
      - path: source-crs/required/networking/metallb/metallbSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # update NROP
      - path: source-crs/required/scheduling/NROPSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "4.19"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      - path: source-crs/required/scheduling/sched.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            #cacheResyncPeriod: "0"
            # Image spec should be the latest for the release
            imageSpec: "registry.ecore.lab.eng.tlv2.redhat.com:5000/nrop/noderesourcetopology-scheduler-rhel9:v4.19.0"
      # update NMState
      - path: source-crs/required/networking/NMStateSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # udpate ClusterLogging
      - path: source-crs/optional/logging/ClusterLogSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
  #
  # MCPs more likely should be unpaused one by one manually so they are updated,
  # within dedicated maintenance windows.
  #
  - name: upgrade-unpause-mcps
    evaluationInterval:
      compliant: never
    manifests:
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: customcnf
              labels:
                machineconfiguration.openshift.io/role: customcnf
                pools.operator.machineconfiguration.openshift.io/customcnf: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, customcnf]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/customcnf: ""
              $patch: replace
              paused: false
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: standard
              labels:
                machineconfiguration.openshift.io/role: standard
                pools.operator.machineconfiguration.openshift.io/standard: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, standard]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/standard: ""
              $patch: replace
              paused: false
