---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: update-4.20
policyDefaults:
  namespace: ztp-update
  policySets: []
  placement:
    clusterSelectors:
      site: "ecore"
      yp-ztp-update: ""
  remediationAction: "inform"
policies:
  #
  # Prepare for update to 4.20
  #
  - name: update-prep-20-catsrc
    manifests:
      #
      # Update catalogsource to point to latest versions
      #
      - path: source-crs/required/other/catalog-source.yaml
        patches:
        - metadata:
            name: redhat-operators-disconnected
            annotations:
              ran.openshift.io/ztp-deploy-wave: "1"
          spec:
            displayName: Red Hat Disconnected Operators Catalog
            image: registry.ecore.lab.eng.tlv2.redhat.com:5000/olm/redhat-operators:v4.20
            publisher: Red Hat
            sourceType: grpc
  - name: update-prep-20-mcps
    evaluationInterval:
      compliant: never
    manifests:
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: customcnf
              labels:
                machineconfiguration.openshift.io/role: customcnf
                pools.operator.machineconfiguration.openshift.io/customcnf: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, customcnf]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/customcnf: ""
              $patch: replace
              paused: true
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: standard
              labels:
                machineconfiguration.openshift.io/role: standard
                pools.operator.machineconfiguration.openshift.io/standard: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, standard]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/standard: ""
              $patch: replace
              paused: true
      #
      # Provide admin ack for deprecated API
      # TODO(yprokule): check if this is needed during 4.19 to 4.19 update.
      #
      #- path: source-crs/GenericConfigMap.yaml
      #  patches:
      #    - metadata:
      #        name: admin-acks
      #        namespace: openshift-config
      #      data:
      #        ack-4.15-kube-1.29-api-removals-in-4.16: "true"
  #
  # Update operators
  #
  - name: update-olm-20
    manifests:
      # update ODF
      - path: source-crs/required/storage/odf-external/odfSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable-4.20"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # update SR-IOV
      - path: source-crs/required/networking/sriov/SriovSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # update MetalLB
      - path: source-crs/required/networking/metallb/metallbSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # update NROP
      - path: source-crs/required/scheduling/NROPSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "4.20"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      - path: source-crs/required/scheduling/sched.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            #cacheResyncPeriod: "0"
            # Image spec should be the latest for the release
            imageSpec: "registry.ecore.lab.eng.tlv2.redhat.com:5000/nrop/noderesourcetopology-scheduler-rhel9:v4.20.0"
      # update NMState
      - path: source-crs/required/networking/NMStateSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # udpate ClusterLogging
      #- path: source-crs/optional/logging/ClusterLogSubscription.yaml
      #  patches:
      #  - metadata:
      #      annotations:
      #        ran.openshift.io/ztp-deploy-wave: "2"
      #    spec:
      #      channel: "stable"
      #      source: redhat-operators-disconnected
      #      installPlanApproval: Manual
  #
  # Perform cluster upgrade
  #
  - name: update-ocp-20
    manifests:
      - path: source-crs/ClusterVersion.yaml
        patches:
        - spec:
            channel: stable-4.20
            upstream: http://registry.ecore.lab.eng.tlv2.redhat.com:8090/yp-graph
            #
            #
            #
            desiredUpdate:
              version: 4.20.0-ec.3
              image: registry.ecore.lab.eng.tlv2.redhat.com:5005/openshift-release-dev/ocp-release@sha256:ea2d94a4f166d94e512d2721474eadecf2b6258b2f11ed31f8800b5106a773d0
              force: true
        - status:
            history:
            - version: 4.20.0-ec.3
              state: "Completed"
  #
  # MCPs more likely should be unpaused one by one manually so they are updated,
  # within dedicated maintenance windows.
  #
  - name: update-unpause-mcps-20
    evaluationInterval:
      compliant: never
    manifests:
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: customcnf
              labels:
                machineconfiguration.openshift.io/role: customcnf
                pools.operator.machineconfiguration.openshift.io/customcnf: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, customcnf]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/customcnf: ""
              $patch: replace
              paused: false
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: standard
              labels:
                machineconfiguration.openshift.io/role: standard
                pools.operator.machineconfiguration.openshift.io/standard: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, standard]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/standard: ""
              $patch: replace
              paused: false
