---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: upgrade-19
policyDefaults:
  namespace: ztp-update
  policySets: []
  placement:
    clusterSelectors:
      site: "ecore"
      yp-ztp-upgrade: ""
  remediationAction: "inform"
policies:
  #
  # Prepare for upgrade to 4.19
  #
  - name: upgrade-prep-19-catsrc
    manifests:
      #
      # Update catalogsource to point to latest versions
      #
      - path: source-crs/required/other/catalog-source.yaml
        patches:
        - metadata:
            name: redhat-operators-disconnected
            annotations:
              ran.openshift.io/ztp-deploy-wave: "1"
          spec:
            displayName: Red Hat Disconnected Operators Catalog
            image: registry.ecore.lab.eng.tlv2.redhat.com:5000/olm/redhat-operators:v4.19
            publisher: Red Hat
            sourceType: grpc
  - name: upgrade-prep-19-mcps
    evaluationInterval:
      compliant: never
    manifests:
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: customcnf
              labels:
                machineconfiguration.openshift.io/role: customcnf
                pools.operator.machineconfiguration.openshift.io/customcnf: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, customcnf]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/customcnf: ""
              $patch: replace
              paused: true
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: standard
              labels:
                machineconfiguration.openshift.io/role: standard
                pools.operator.machineconfiguration.openshift.io/standard: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, standard]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/standard: ""
              $patch: replace
              paused: true
      #
      # Provide admin ack for deprecated API
      # TODO(yprokule): check if this is needed during 4.17 to 4.18 update.
      #
      #- path: source-crs/GenericConfigMap.yaml
      #  patches:
      #    - metadata:
      #        name: admin-acks
      #        namespace: openshift-config
      #      data:
      #        ack-4.15-kube-1.29-api-removals-in-4.16: "true"
  #
  # Update operators
  #
  - name: upgrade-olm-19
    manifests:
      # update ODF
      - path: source-crs/required/storage/odf-external/odfSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable-4.19"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # update SR-IOV
      - path: source-crs/required/networking/sriov/SriovSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # update MetalLB
      - path: source-crs/required/networking/metallb/metallbSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # update NROP
      - path: source-crs/required/scheduling/NROPSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "4.19"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      - path: source-crs/required/scheduling/sched.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            #cacheResyncPeriod: "0"
            # Image spec should be the latest for the release
            imageSpec: "registry.ecore.lab.eng.tlv2.redhat.com:5000/nrop/noderesourcetopology-scheduler-rhel9:v4.19.0"
      # update NMState
      - path: source-crs/required/networking/NMStateSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
      # udpate ClusterLogging
      - path: source-crs/optional/logging/ClusterLogSubscription.yaml
        patches:
        - metadata:
            annotations:
              ran.openshift.io/ztp-deploy-wave: "2"
          spec:
            channel: "stable"
            source: redhat-operators-disconnected
            installPlanApproval: Manual
  #
  # Perform cluster upgrade
  #
  - name: upgrade-ocp-19
    manifests:
      - path: source-crs/ClusterVersion.yaml
        patches:
        - spec:
            channel: stable-4.19
            upstream: http://registry.ecore.lab.eng.tlv2.redhat.com:8090/yp-graph
            #
            # TODO: update this when 4.19 builds are ready
            #
            desiredUpdate:
              version: 4.17.0-ec.2
              image: registry.ecore.lab.eng.tlv2.redhat.com:5005/openshift-release-dev/ocp-release@sha256:eeaf087727b4ec3fa36bf2b1e812e48682f0415b9d2d53be83704931172a856c
              force: true
        - status:
            history:
            - version: 4.17.0-ec.2
              state: "Completed"
  #
  # MCPs more likely should be unpaused one by one manually so they are updated,
  # within dedicated maintenance windows.
  #
  - name: upgrade-unpause-mcps
    evaluationInterval:
      compliant: never
    manifests:
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: customcnf
              labels:
                machineconfiguration.openshift.io/role: customcnf
                pools.operator.machineconfiguration.openshift.io/customcnf: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, customcnf]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/customcnf: ""
              $patch: replace
              paused: false
      - path: qe-source-crs/CustomMCP.yaml
        patches:
          - metadata:
              name: standard
              labels:
                machineconfiguration.openshift.io/role: standard
                pools.operator.machineconfiguration.openshift.io/standard: ""
            spec:
              machineConfigSelector:
                matchExpressions:
                  - key: machineconfiguration.openshift.io/role
                    operator: In
                    values: [worker, standard]
              nodeSelector:
                matchLabels:
                  $patch: replace
                  node-role.kubernetes.io/standard: ""
              $patch: replace
              paused: false
