---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "operators"
  namespace: "ztp-common"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
    version: "4.17"
  bindingExcludedRules:
    yp-ztp-update: ""
  remediationAction: inform
  sourceFiles:
    - fileName: required/other/catalog-source.yaml
      policyName: "config-catsrc"
      metadata:
        name: redhat-operators-disconnected
        annotations:
          ran.openshift.io/ztp-deploy-wave: "1"
      spec:
        displayName: Red Hat Disconnected Operators Catalog
        image: registry.ecore.lab.eng.tlv2.redhat.com:5000/olm/redhat-operators:v4.17
        publisher: Red Hat
        sourceType: grpc
    #
    # install and configure SR-IOV operator
    #
    - fileName: required/networking/sriov/SriovSubscriptionNS.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/networking/sriov/SriovSubscriptionOperGroup.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/networking/sriov/SriovSubscription.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
      spec:
        channel: "stable"
        source: redhat-operators-disconnected
        installPlanApproval: "Automatic"
    #
    # install and configure MetalLB operator
    # MetalLB operator configuration moved to a site folder
    #
    - fileName: required/networking/metallb/metallbNS.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/networking/metallb/metallbOperGroup.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/networking/metallb/metallbSubscription.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
      spec:
        channel: "stable"
        source: redhat-operators-disconnected
        installPlanApproval: "Automatic"
    #
    # install and configure NROP
    #
    - fileName: required/scheduling/NROPSubscriptionNS.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/scheduling/NROPSubscriptionOperGroup.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/scheduling/NROPSubscription.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
      spec:
        channel: "4.17"
        source: redhat-operators-disconnected
    #
    # install NMState operator
    #
    - fileName: required/networking/NMStateNS.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/networking/NMStateOperGroup.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/networking/NMStateSubscription.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    #
    # install and configure Logging
    #
    #- fileName: optional/logging/ClusterLogNS.yaml
    #  policyName: "install-operators"
    #  metadata:
    #    annotations:
    #      ran.openshift.io/ztp-deploy-wave: "2"
    #- fileName: optional/logging/ClusterLogOperGroup.yaml
    #  policyName: "install-operators"
    #  metadata:
    #    annotations:
    #      ran.openshift.io/ztp-deploy-wave: "2"
    #- fileName: optional/logging/ClusterLogSubscription.yaml
    #  policyName: "install-operators"
    #  metadata:
    #    annotations:
    #      ran.openshift.io/ztp-deploy-wave: "2"
    #  spec:
    #    source: redhat-operators-disconnected
    #    installPlanApproval: Automatic
    #
    # NOTE(yprokule): ClusterLogging instance by default uses wave 10
    #               : trying to use same wave
    #- fileName: optional/logging/ClusterLogging.yaml
    #  policyName: "install-operators"
    #  metadata:
    #    annotations:
    #      ran.openshift.io/ztp-deploy-wave: "2"
    #
    # install ODF operator
    #
    - fileName: required/storage/odf-external/odfNS.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/storage/odf-external/odfOperGroup.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
    - fileName: required/storage/odf-external/odfSubscription.yaml
      policyName: "install-operators"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
      spec:
        channel: "stable-4.17"
