apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: rh-disconnected-icsp
spec:
  repositoryDigestMirrors:
  #- mirrors:
  #  - registry.ecore.lab.eng.tlv2.redhat.com:5000/openshift-release-dev/ocp-v4.0-art-dev
  #  - registry.ecore.lab.eng.tlv2.redhat.com:5000/ocp/release
  #  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  #- mirrors:
  #  - registry.ecore.lab.eng.tlv2.redhat.com:5000/openshift-release-dev/ocp-v4.0-art-dev
  #  - registry.ecore.lab.eng.tlv2.redhat.com:5000/ocp/release
  #  source: registry.ci.openshift.org/ocp/release
  - mirrors:
    - registry.ecore.lab.eng.tlv2.redhat.com:5005/openshift-release-dev/ocp-v4.0-art-dev
    - registry.ecore.lab.eng.tlv2.redhat.com:5005/ocp/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - registry.ecore.lab.eng.tlv2.redhat.com:5005/openshift-release-dev/ocp-v4.0-art-dev
    - registry.ecore.lab.eng.tlv2.redhat.com:5005/ocp/release
    source: registry.ci.openshift.org/ocp/release
  - mirrors:
    - registry.ecore.lab.eng.tlv2.redhat.com:5000
    source: registry.redhat.io
  - mirrors:
    - registry.ecore.lab.eng.tlv2.redhat.com:5000
    source: registry-proxy.engineering.redhat.com
  - mirrors:
    - registry.ecore.lab.eng.tlv2.redhat.com:5000
    source: registry.stage.redhat.io
  - mirrors:
    - registry.ecore.lab.eng.tlv2.redhat.com:5000/openshift-qe-optional-operators
    source: quay.io/openshift-qe-optional-operators
  - mirrors:
    - registry.ecore.lab.eng.tlv2.redhat.com:5000/openshifttest
    source: quay.io/openshifttest
  - mirrors:
    - registry.ecore.lab.eng.tlv2.redhat.com:5000/rh-nfv-int
    source: quay.io/rh-nfv-int
  - mirrors:
    - registry.ecore.lab.eng.tlv2.redhat.com:5000/intel
    source: registry.connect.redhat.com/intel
