---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: disconnected-internal-idms
spec:
  imageDigestMirrors:
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005/openshift-release-dev/ocp-v4.0-art-dev
        - registry.ecore.lab.eng.tlv2.redhat.com:5005/ocp/release
      source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005/openshift-release-dev/ocp-v4.0-art-dev
        - registry.ecore.lab.eng.tlv2.redhat.com:5005/ocp/release
      source: registry.ci.openshift.org/ocp/release
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005
      source: registry.redhat.io
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005
      source: registry-proxy.engineering.redhat.com
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005
      source: registry.stage.redhat.io
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005/openshift-qe-optional-operators
      source: quay.io/openshift-qe-optional-operators
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005/openshifttest
      source: quay.io/openshifttest
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005/rh-nfv-int
      source: quay.io/rh-nfv-int
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005/intel
      source: registry.connect.redhat.com/intel
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005
      source: quay.io/prega/test
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5005/openshift-release-dev/ocp-release-nightly
      source: quay.io/openshift-release-dev/ocp-release-nightly
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-odf-rhel9-operator
      source: registry.redhat.io/odf4/odf-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-odf-console-rhel9
      source: registry.redhat.io/odf4/odf-console-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-ocs-rhel9-operator
      source: registry.redhat.io/odf4/ocs-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-cephcsi-rhel9-operator
      source: registry.redhat.io/odf4/cephcsi-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-odf-csi-addons-rhel9-operator
      source: registry.redhat.io/odf4/odf-csi-addons-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-ocs-client-rhel9-operator
      source: registry.redhat.io/odf4/ocs-client-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-ocs-metrics-exporter-rhel9
      source: registry.redhat.io/odf4/ocs-metrics-exporter-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-odf-external-snapshotter-rhel9-operator
      source: registry.redhat.io/odf4/odf-external-snapshotter-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-rook-ceph-rhel9-operator
      source: registry.redhat.io/odf4/rook-ceph-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/openshift-ose-oauth-proxy-rhel9
      source: registry.redhat.io/openshift4/ose-oauth-proxy-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-cephcsi-rhel9-operator
      source: registry.redhat.io/odf4/cephcsi-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-odf-cloudnative-pg-rhel9-operator
      source: registry.redhat.io/odf4/odf-cloudnative-pg-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-mcg-rhel9-operator
      source: registry.redhat.io/odf4/mcg-rhel9-operator
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-ocs-client-console-rhel9
      source: registry.redhat.io/odf4/ocs-client-console-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-odf-csi-addons-sidecar-rhel9
      source: registry.redhat.io/odf4/odf-csi-addons-sidecar-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-cephcsi-rhel9
      source: registry.redhat.io/odf4/cephcsi-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-odf-external-snapshotter-sidecar-rhel9
      source: registry.redhat.io/odf4/odf-external-snapshotter-sidecar-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/openshift-ose-csi-external-provisioner-rhel9
      source: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/openshift-ose-csi-external-resizer-rhel9
      source: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/openshift-ose-csi-external-attacher-rhel9
      source: registry.redhat.io/openshift4/ose-csi-external-attacher-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/openshift-ose-csi-node-driver-registrar-rhel9
      source: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-mcg-core-rhel9
      source: registry.redhat.io/odf4/mcg-core-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/odf4-odf-external-snapshotter-operator-bundle
      source: quay.io/prega/test/rhceph-dev/odf4-odf-external-snapshotter-operator-bundle
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/openshift-ose-csi-external-snapshotter-rhel9
      source: registry.redhat.io/openshift4/ose-csi-external-snapshotter-rhel9
    - mirrors:
        - registry.ecore.lab.eng.tlv2.redhat.com:5000/prega/test/rhceph-dev/rhceph-8-rhel9
      source: registry.redhat.io/rhceph/rhceph-8-rhel9
