---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  creationTimestamp: null
  labels:
    machineconfiguration.openshift.io/role: master
  name: 45-enable-forwarding-master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,IyBOZWVkZWQgYnkgdGhlIE9wZW5TaGlmdC4gRm9yIG1vcmUgZGV0YWlscyBzZWUKIyBodHRwczovL2lzc3Vlcy5yZWRoYXQuY29tL2Jyb3dzZS9PQ1BCVUdTLTE2MDUxCm5ldC5pcHY0LmNvbmYuYm9uZDAvMzU1LmZvcndhcmRpbmcgPSAxCg==
        mode: 420
        overwrite: true
        path: /etc/sysctl.d/qe-forwarding.conf
