---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: standard
  labels:
    machineconfiguration.openshift.io/role: standard
    pools.operator.machineconfiguration.openshift.io/standard: ""
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values: [ worker, standard ]
  paused: false
  maxUnavailable: 1
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/standard: ""
