---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "ht-worker-config"
  namespace: "ztp-site"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  mcp: "ht100gb"
  sourceFiles:
    #
    # configure MachineConfigPool ht100gb moved to extra-manifests
    # but also present in policies/TS-1.6/sites/n65-ocp1/config-ht-nodes.yaml
    #
    - fileName: MachineConfigPool.yaml
      policyName: config-nodes-mcp
      metadata:
        name: ht100gb
        annotations:
          ran.openshift.io/ztp-deploy-wave: "2"
        labels:
          machineconfiguration.openshift.io/role: ht100gb
          pools.operator.machineconfiguration.openshift.io/ht100gb: ""
      spec:
        machineConfigSelector:
          matchExpressions:
            - key: machineconfiguration.openshift.io/role
              operator: In
              values: [worker, ht100gb]
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/ht100gb: ""
    # configure SR-IOV Network Node Policy
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-nnp"
      metadata:
        name: sriovleftdpdkmellanox
      spec:
        resourceName: "sriovleftdpdkmellanox"
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        mtu: 9000
        numVfs: 4
        priority: 99
        nicSelector:
          # consider switching to PCI paths
          pfNames: ['ens4f0np0', 'ens5f0np0']
        deviceType: netdevice
        isRdma: True
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "sriov-nnp"
      metadata:
        name: sriovrightdpdkmellanox
      spec:
        resourceName: "sriovrightdpdkmellanox"
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        mtu: 9000
        numVfs: 4
        priority: 99
        nicSelector:
          # consider switching to PCI paths
          pfNames: ['ens4f1np1', 'ens5f1np1']
        deviceType: netdevice
        isRdma: True
    # configure SR-IOV Networks
    - fileName: SriovNetwork.yaml
      policyName: config-sriov-network
      metadata:
        name: "sriov-net-one"
      spec:
        capabilities: '{ "ips": true }'
        ipam: '{}'
        linkState: auto
        networkNamespace: rds-sriov-wlkd
        resourceName: sriovleftdpdkmellanox
        trust: "on"
    - fileName: SriovNetwork.yaml
      policyName: config-sriov-network
      metadata:
        name: "sriov-net-two"
      spec:
        capabilities: '{ "ips": true }'
        ipam: '{}'
        linkState: auto
        networkNamespace: rds-sriov-wlkd
        resourceName: sriovrightdpdkmellanox
        trust: "on"
    # configure performance profile
    - fileName: PerformanceProfile.yaml
      policyName: "post-install-tunning"
      complianceType: mustonlyhave
      metadata:
        name: ht100gb
        annotations:
          # this is needed for CGroupsV2 testing
          performance.openshift.io/ignore-cgroups-version: "true"
          # Some pods want the kernel stack to ignore IPv6 router Advertisement.
          kubeletconfig.experimental: |
            {"allowedUnsafeSysctls":["net.ipv6.conf.all.accept_ra"]}
      spec:
        additionalKernelArgs: []
        cpu:
          isolated: 1-25,27-51,53-77,79-103
          reserved: 0,26,52,78
        globallyDisableIrqLoadBalancing: false
        hugepages:
          defaultHugepagesSize: 1G
          pages:
          - size: 1G
            count: 6
            node: 0
          - size: 1G
            count: 6
            node: 1
        machineConfigPoolSelector:
          pools.operator.machineconfiguration.openshift.io/ht100gb: ""
        nodeSelector:
          node-role.kubernetes.io/ht100gb: ""
        workloadHints:
          realTime: false
          highPowerConsumption: false
          perPodPowerManagement: true
        realTimeKernel:
          enabled: false
        numa:
          topologyPolicy: single-numa-node
        # TODO(yprokule): check usage of `net` directive
        net:
          devices:
          - interfaceName: ens4*
          - interfaceName: ens5*
          userLevelNetworking: true
