apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: telco-metallb
policyDefaults:
  namespace: ztp-site
  policySets: []
  placement:
    labelSelector:
      matchExpressions:
        - key: site
          operator: In
          values:
            - "ecore"
        - key: zone
          operator: In
          values:
            - tlv2
  remediationAction: "inform"
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
policies:
  - name: configure-metallb
    manifests:
      - path: source-crs/required/networking/metallb/metallb.yaml
        patches:
          - spec:
              logLevel: debug

      - path: source-crs/required/networking/metallb/bfd-profile.yaml
        patches:
          - metadata:
              name: bfd-profile
            spec:
              receiveInterval: 150
              transmitInterval: 100
              detectMultiplier: 3
              echoInterval: 300
              echoMode: false
              passiveMode: false
              minimumTtl: 254

      - path: source-crs/required/networking/metallb/bgp-peer.yaml
        patches:
          - metadata:
              name: greenpeers
            spec:
              keepaliveTime: 0s
              peerAddress: 10.46.188.2
              peerASN: 65435
              myASN: 65450
              holdTime: 3m0s
              bfdProfile: bfd-profile
              peerPort: 179
              nodeSelectors:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - openshift-worker-0.ecore.lab.eng.tlv2.redhat.com
                        - openshift-worker-1.ecore.lab.eng.tlv2.redhat.com
                        - openshift-worker-2.ecore.lab.eng.tlv2.redhat.com
                        - openshift-worker-3.ecore.lab.eng.tlv2.redhat.com
              $patch: replace
              routerID: null

      - path: source-crs/required/networking/metallb/bgp-peer.yaml
        patches:
          - metadata:
              name: greenpeers-ipv6
            spec:
              keepaliveTime: 0s
              peerAddress: 2620:52:0:2ebc::5
              peerASN: 65435
              myASN: 65450
              holdTime: 3m0s
              bfdProfile: bfd-profile
              peerPort: 179
              nodeSelectors:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - openshift-worker-0.ecore.lab.eng.tlv2.redhat.com
                        - openshift-worker-1.ecore.lab.eng.tlv2.redhat.com
                        - openshift-worker-2.ecore.lab.eng.tlv2.redhat.com
                        - openshift-worker-3.ecore.lab.eng.tlv2.redhat.com
              $patch: replace
              routerID: null

      - path: source-crs/required/networking/metallb/community.yaml
        patches:
          - spec:
              communities:
                - name: greenc
                  value: '7003:008'

      - path: source-crs/required/networking/metallb/bgp-advr.yaml
        patches:
          - metadata:
              name: green
            spec:
              communities:
                - greenc
              ipAddressPools:
                - greenips
              peers:
                - greenpeers
                - greenpeers-ipv6

      - path: source-crs/required/networking/metallb/addr-pool.yaml
        patches:
          - metadata:
              name: greenips
              $patch: replace
              annotations: nul
            spec:
              autoAssign: false
              # in ecore setup(registry.ecore.lab.eng.tlv2.redhat.com)
              # this is LB-OAM vlan
              addresses:
                - 10.46.188.20/32
                - 10.46.188.21/32
                - 10.46.188.22/32
                - 2620:0052:0000:2ebc::0020/128
                - 2620:0052:0000:2ebc::0021/128
                - 2620:0052:0000:2ebc::0022/128
