apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: telco-config-ht
policyDefaults:
  namespace: ztp-site
  policySets: []
  placement:
    labelSelector:
      matchExpressions:
        - key: site
          operator: In
          values:
            - "ecore"
        - key: zone
          operator: In
          values:
            - tlv2
  remediationAction: "inform"
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
policies:
  - name: config-sriov-operator
    manifests:
      - path: source-crs/required/networking/sriov/sriovNetworkNodePolicy.yaml
        patches:
          - metadata:
              name: sriovleftdpdkintel
            spec:
              resourceName: "sriovleftdpdkintel"
              nodeSelector:
                node-role.kubernetes.io/customcnf: ""
              mtu: '{{hub fromConfigMap "" "sriov-config" "sriov-nncp-one-mtu" | toInt hub}}'
              numVfs: '{{hub fromConfigMap "" "sriov-config" "sriov-nncp-one-num-vfs" | toInt hub}}'
              priority: 99
              nicSelector:
                # consider switching to PCI paths
                # pfNames: ['ens4f0np0', 'ens5f0np0']
                pfNames: '{{hub fromConfigMap "" "sriov-config" (printf "%s-sriov-node-policy-1-pfNames" (index .ManagedClusterLabels "group")) | toLiteral hub}}'
              deviceType: netdevice
              isRdma: False

      - path: source-crs/required/networking/sriov/sriovNetworkNodePolicy.yaml
        patches:
          - metadata:
              name: sriovrightdpdkintel
            spec:
              resourceName: "sriovrightdpdkintel"
              nodeSelector:
                node-role.kubernetes.io/customcnf: ""
              mtu: '{{hub fromConfigMap "" "sriov-config" "sriov-nncp-two-mtu" | toInt hub}}'
              numVfs: '{{hub fromConfigMap "" "sriov-config" "sriov-nncp-two-num-vfs" | toInt hub}}'
              priority: 99
              nicSelector:
                # consider switching to PCI paths
                # pfNames: ['ens4f1np1', 'ens5f1np1']
                pfNames: '{{hub fromConfigMap "" "sriov-config" (printf "%s-sriov-node-policy-2-pfNames" (index .ManagedClusterLabels "group")) | toLiteral hub}}'
              deviceType: netdevice
              isRdma: False

      - path: source-crs/required/networking/sriov/sriovNetwork.yaml
        patches:
          - metadata:
              name: "sriov-net-one"
            spec:
              capabilities: '{ "ips": true }'
              ipam: '{}'
              linkState: auto
              networkNamespace: rds-sriov-wlkd
              resourceName: sriovleftdpdkintel
              trust: "on"

      - path: source-crs/required/networking/sriov/sriovNetwork.yaml
        patches:
          - metadata:
              name: "sriov-net-two"
            spec:
              capabilities: '{ "ips": true }'
              ipam: '{}'
              linkState: auto
              networkNamespace: rds-sriov-wlkd
              resourceName: sriovrightdpdkintel
              trust: "on"

  - name: config-perf-profile
    manifests:
      - path: source-crs/required/performance/PerformanceProfile.yaml
        complianceType: mustonlyhave
        patches:
          - metadata:
              name: customcnf
              annotations:
                # this is needed for CGroupsV2 testing
                performance.openshift.io/ignore-cgroups-version: "true"
                # Some pods want the kernel stack to ignore IPv6 router Advertisement.
                kubeletconfig.experimental: |
                  {"allowedUnsafeSysctls":["net.ipv6.conf.all.accept_ra"]}
            spec:
              additionalKernelArgs: []
              cpu:
                isolated: '{{hub fromConfigMap "" "hw-types" (printf "%s-cnf-isolated-cpu" .ManagedClusterName) | toLiteral hub}}'
                reserved: '{{hub fromConfigMap "" "hw-types" (printf "%s-cnf-reserved-cpu" .ManagedClusterName) | toLiteral hub}}'
              globallyDisableIrqLoadBalancing: false
              hugepages:
                defaultHugepagesSize: 1G
                pages:
                - size: 1G
                  count: 6
                  node: 0
                - size: 1G
                  count: 6
                  node: 1
              machineConfigPoolSelector:
                $patch: replace
                pools.operator.machineconfiguration.openshift.io/customcnf: ""
              nodeSelector:
                $patch: replace
                node-role.kubernetes.io/customcnf: ""
              workloadHints:
                realTime: false
                highPowerConsumption: false
                perPodPowerManagement: true
              realTimeKernel:
                enabled: false
              numa:
                topologyPolicy: single-numa-node
              # TODO(yprokule): check usage of `net` directive
              net:
                devices:
                - interfaceName: ens4*
                - interfaceName: ens5*
                userLevelNetworking: true
