apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: telco-config-nodes
policyDefaults:
  namespace: ztp-site
  policySets: []
  placement:
    labelSelector:
      matchExpressions:
        - key: site
          operator: In
          values:
            - "ecore"
        - key: zone
          operator: In
          values:
            - tlv2
  remediationAction: "inform"
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "4"
policies:
  - name: config-mc
    manifests:
      - path: source-crs/MachineConfigGeneric.yaml
        patches:
          - metadata:
              name: 98-master-etc-chrony-conf
              $patch: replace
              labels:
                machineconfiguration.openshift.io/role: master
            spec:
              config:
                # Release info found in https://github.com/coreos/butane/releases
                ignition:
                  version: 3.2.0
                storage:
                  files:
                  - contents:
                      source: data:text/plain;charset=utf-8;base64,c2VydmVyIHJlZ2lzdHJ5LmVjb3JlLmxhYi5lbmcudGx2Mi5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgbnRwMS5udHAtMDAxLnByb2QuaWFkMi5kYy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgbnRwMi5udHAtMDAxLnByb2QuaWFkMi5kYy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2sxLmJvcy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2syLmJvcy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2suY29ycC5yZWRoYXQuY29tIGlidXJzdApzdHJhdHVtd2VpZ2h0IDAKZHJpZnRmaWxlIC92YXIvbGliL2Nocm9ueS9kcmlmdApydGNzeW5jCm1ha2VzdGVwIDEwIDMKYmluZGNtZGFkZHJlc3MgMTI3LjAuMC4xCmJpbmRjbWRhZGRyZXNzIDo6MQprZXlmaWxlIC9ldGMvY2hyb255LmtleXMKbm9jbGllbnRsb2cKbG9nY2hhbmdlIDAuNQpsb2dkaXIgL3Zhci9sb2cvY2hyb255Cg==
                      verification: {}
                    filesystem: root
                    group:
                      name: root
                    mode: 420
                    path: /etc/chrony.conf
                    user:
                      name: root

      - path: source-crs/MachineConfigGeneric.yaml
        patches:
          - metadata:
              name: 98-worker-etc-chrony-conf
              $patch: replace
              labels:
                machineconfiguration.openshift.io/role: worker
            spec:
              config:
                # Release info found in https://github.com/coreos/butane/releases
                ignition:
                  version: 3.2.0
                storage:
                  files:
                  - contents:
                      source: data:text/plain;charset=utf-8;base64,c2VydmVyIHJlZ2lzdHJ5LmVjb3JlLmxhYi5lbmcudGx2Mi5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgbnRwMS5udHAtMDAxLnByb2QuaWFkMi5kYy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgbnRwMi5udHAtMDAxLnByb2QuaWFkMi5kYy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2sxLmJvcy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2syLmJvcy5yZWRoYXQuY29tIGlidXJzdApzZXJ2ZXIgY2xvY2suY29ycC5yZWRoYXQuY29tIGlidXJzdApzdHJhdHVtd2VpZ2h0IDAKZHJpZnRmaWxlIC92YXIvbGliL2Nocm9ueS9kcmlmdApydGNzeW5jCm1ha2VzdGVwIDEwIDMKYmluZGNtZGFkZHJlc3MgMTI3LjAuMC4xCmJpbmRjbWRhZGRyZXNzIDo6MQprZXlmaWxlIC9ldGMvY2hyb255LmtleXMKbm9jbGllbnRsb2cKbG9nY2hhbmdlIDAuNQpsb2dkaXIgL3Zhci9sb2cvY2hyb255Cg==
                      verification: {}
                    filesystem: root
                    group:
                      name: root
                    mode: 420
                    path: /etc/chrony.conf
                    user:
                      name: root
