---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "day2-net-intersite"
  namespace: "ztp-site"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    - fileName: nmstate/nodeNetworkConfigurationPolicy.yaml
      policyName: "add-lb-intersite-vlan-interface"
      metadata:
        name: openshift-master-0-lb-intersite-vlan-interface
      annotations:
        ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        nodeSelector:
          kubernetes.io/hostname: "openshift-master-0.ecore.lab.eng.tlv2.redhat.com"
        desiredState:
          interfaces:
            - name: bond0.357
              description: "This is lb-signaling VLAN"
              type: vlan
              state: up
              ipv4:
                enabled: true
                address:
                - ip: 10.46.187.200
                  prefix-length: 26
                dhcp: false
                auto-dns: false
              ipv6:
                enabled: false
                dhcp: false
                auto-dns: false
              vlan:
                base-iface: bond0
                id: 357
    # master-0 end ^^^
    - fileName: nmstate/nodeNetworkConfigurationPolicy.yaml
      policyName: "add-lb-intersite-vlan-interface"
      metadata:
        name: openshift-master-1-lb-intersite-vlan-interface
      annotations:
        ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        nodeSelector:
          kubernetes.io/hostname: "openshift-master-1.ecore.lab.eng.tlv2.redhat.com"
        desiredState:
          interfaces:
            - name: bond0.357
              description: "This is lb-intersite VLAN"
              type: vlan
              state: up
              ipv4:
                enabled: true
                address:
                - ip: 10.46.187.201
                  prefix-length: 26
                dhcp: false
                auto-dns: false
              ipv6:
                enabled: false
                dhcp: false
                auto-dns: false
              vlan:
                base-iface: bond0
                id: 357
    # master-1 end ^^^
    - fileName: nmstate/nodeNetworkConfigurationPolicy.yaml
      policyName: "add-lb-intersite-vlan-interface"
      metadata:
        name: openshift-master-2-lb-intersite-vlan-interface
      annotations:
        ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        nodeSelector:
          kubernetes.io/hostname: "openshift-master-2.ecore.lab.eng.tlv2.redhat.com"
        desiredState:
          interfaces:
            - name: bond0.357
              description: "This is lb-intersite VLAN"
              type: vlan
              state: up
              ipv4:
                enabled: true
                address:
                - ip: 10.46.187.202
                  prefix-length: 26
                dhcp: false
                auto-dns: false
              ipv6:
                enabled: false
                dhcp: false
                auto-dns: false
              vlan:
                base-iface: bond0
                id: 357
    # master-2 end ^^^
    - fileName: nmstate/nodeNetworkConfigurationPolicy.yaml
      policyName: "add-lb-intersite-vlan-interface"
      metadata:
        name: openshift-worker-0-lb-intersite-vlan-interface
      annotations:
        ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        nodeSelector:
          kubernetes.io/hostname: "openshift-worker-0.ecore.lab.eng.tlv2.redhat.com"
        desiredState:
          interfaces:
            - name: bond0.357
              description: "This is lb-intersite VLAN"
              type: vlan
              state: up
              ipv4:
                enabled: true
                address:
                - ip: 10.46.187.203
                  prefix-length: 26
                dhcp: false
                auto-dns: false
              ipv6:
                enabled: false
                dhcp: false
                auto-dns: false
              vlan:
                base-iface: bond0
                id: 357
    # worker-0 end ^^^
    - fileName: nmstate/nodeNetworkConfigurationPolicy.yaml
      policyName: "add-lb-intersite-vlan-interface"
      metadata:
        name: openshift-worker-1-lb-intersite-vlan-interface
      annotations:
        ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        nodeSelector:
          kubernetes.io/hostname: "openshift-worker-1.ecore.lab.eng.tlv2.redhat.com"
        desiredState:
          interfaces:
            - name: bond0.357
              description: "This is lb-intersite VLAN"
              type: vlan
              state: up
              ipv4:
                enabled: true
                address:
                - ip: 10.46.187.204
                  prefix-length: 26
                dhcp: false
                auto-dns: false
              ipv6:
                enabled: false
                dhcp: false
                auto-dns: false
              vlan:
                base-iface: bond0
                id: 357
    # worker-1 end ^^^
