---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "networks-qe"
  namespace: "ztp-site"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    - fileName: required/networking/metallb/metallb.yaml
      policyName: "config-metallb"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        logLevel: debug
    - fileName: required/networking/metallb/bfd-profile.yaml
      policyName: "config-metallb"
      metadata:
        name: bfd-profile
        annotations:
          ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        receiveInterval: 150
        transmitInterval: 100
        detectMultiplier: 3
        echoInterval: 300
        echoMode: false
        passiveMode: false
        minimumTtl: 254
    - fileName: required/networking/metallb/bgp-peer.yaml
      policyName: "config-metallb"
      metadata:
        name: greenpeers
        annotations:
          ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        keepaliveTime: 0s
        peerAddress: 10.46.188.2
        peerASN: 65435
        myASN: 65450
        holdTime: 3m0s
        bfdProfile: bfd-profile
        peerPort: 179
        nodeSelectors:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - openshift-worker-0.ecore.lab.eng.tlv2.redhat.com
                  - openshift-worker-1.ecore.lab.eng.tlv2.redhat.com
                  - openshift-worker-2.ecore.lab.eng.tlv2.redhat.com
                  - openshift-worker-3.ecore.lab.eng.tlv2.redhat.com
    - fileName: required/networking/metallb/community.yaml
      policyName: "config-metallb"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        communities:
          - name: greenc
            value: '7003:008'
    - fileName: required/networking/metallb/bgp-advr.yaml
      policyName: "config-metallb"
      metadata:
        name: green
        annotations:
          ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        communities:
          - greenc
        ipAddressPools:
          - greenips
        peers:
          - greenpeers
    - fileName: required/networking/metallb/addr-pool.yaml
      policyName: "config-metallb"
      metadata:
        name: greenips
        annotations:
          ran.openshift.io/ztp-deploy-wave: "10"
      spec:
        autoAssign: false
        # in ecore setup(registry.ecore.lab.eng.tlv2.redhat.com)
        # this is LB-OAM vlan
        addresses:
          - 10.46.188.20/32
          - 10.46.188.21/32
          - 10.46.188.22/32
