---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "odf-storage-tlv2"
  namespace: "ztp-site"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    # install ODF operator
    - fileName: required/storage/odf-external/odfNS.yaml
      policyName: "install-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "8"
    - fileName: required/storage/odf-external/odfOperGroup.yaml
      policyName: "install-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "8"
    - fileName: required/storage/odf-external/odfSubscription.yaml
      policyName: "install-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "8"
      spec:
        channel: "stable-4.16"
    # configure ODF operator
    - fileName: required/storage/odf-external/01-rook-ceph-external-cluster-details.secret.yaml
      policyName: "config-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "11"
      data:
        external_cluster_details: W3sibmFtZSI6ICJyb29rLWNlcGgtbW9uLWVuZHBvaW50cyIsICJraW5kIjogIkNvbmZpZ01hcCIsICJkYXRhIjogeyJkYXRhIjogImNlcGguZWNvcmUubGFiLmVuZy50bHYyLnJlZGhhdC5jb209MTAuNDYuMTg3Ljk5OjY3ODkiLCAibWF4TW9uSWQiOiAiMCIsICJtYXBwaW5nIjogInt9In19LCB7Im5hbWUiOiAicm9vay1jZXBoLW1vbiIsICJraW5kIjogIlNlY3JldCIsICJkYXRhIjogeyJhZG1pbi1zZWNyZXQiOiAiYWRtaW4tc2VjcmV0IiwgImZzaWQiOiAiYzNmYTY0NTgtMmQ2Yi0xMWVmLWI0YzMtNTI1NDAwNTY0MDRlIiwgIm1vbi1zZWNyZXQiOiAibW9uLXNlY3JldCJ9fSwgeyJuYW1lIjogInJvb2stY2VwaC1vcGVyYXRvci1jcmVkcyIsICJraW5kIjogIlNlY3JldCIsICJkYXRhIjogeyJ1c2VySUQiOiAiY2xpZW50LmhlYWx0aGNoZWNrZXIiLCAidXNlcktleSI6ICJBUUFnaFhGbWhqWTdBeEFBb2tYODhQcVFXVC9HRWEzMFByMy9pQT09In19LCB7Im5hbWUiOiAibW9uaXRvcmluZy1lbmRwb2ludCIsICJraW5kIjogIkNlcGhDbHVzdGVyIiwgImRhdGEiOiB7Ik1vbml0b3JpbmdFbmRwb2ludCI6ICIxMC40Ni4xODcuOTkiLCAiTW9uaXRvcmluZ1BvcnQiOiAiOTI4MyJ9fSwgeyJuYW1lIjogImNlcGgtcmJkIiwgImtpbmQiOiAiU3RvcmFnZUNsYXNzIiwgImRhdGEiOiB7InBvb2wiOiAicmJkIn19LCB7Im5hbWUiOiAicm9vay1jc2ktcmJkLW5vZGUiLCAia2luZCI6ICJTZWNyZXQiLCAiZGF0YSI6IHsidXNlcklEIjogImNzaS1yYmQtbm9kZSIsICJ1c2VyS2V5IjogIkFRQWdoWEZtcFQ2UkF4QUFvVnRaUUxnT2ozL2thYjVSOE4zR1ZBPT0ifX0sIHsibmFtZSI6ICJyb29rLWNzaS1yYmQtcHJvdmlzaW9uZXIiLCAia2luZCI6ICJTZWNyZXQiLCAiZGF0YSI6IHsidXNlcklEIjogImNzaS1yYmQtcHJvdmlzaW9uZXIiLCAidXNlcktleSI6ICJBUUFnaFhGbUVndldBeEFBWUFaNDZPYkVaSmxpalVOUDZwQitNdz09In19LCB7Im5hbWUiOiAicm9vay1jc2ktY2VwaGZzLXByb3Zpc2lvbmVyIiwgImtpbmQiOiAiU2VjcmV0IiwgImRhdGEiOiB7ImFkbWluSUQiOiAiY3NpLWNlcGhmcy1wcm92aXNpb25lciIsICJhZG1pbktleSI6ICJBUUFVNkhObWlUN3RMUkFBVlZqL1F5NWFSQXZvN0V3MmVSbGk5UT09In19LCB7Im5hbWUiOiAicm9vay1jc2ktY2VwaGZzLW5vZGUiLCAia2luZCI6ICJTZWNyZXQiLCAiZGF0YSI6IHsiYWRtaW5JRCI6ICJjc2ktY2VwaGZzLW5vZGUiLCAiYWRtaW5LZXkiOiAiQVFBVTZITm04NnVoTFJBQWhpTGNlUyszclB2clgyMUZvSjNUMHc9PSJ9fSwgeyJuYW1lIjogInJvb2stY2VwaC1kYXNoYm9hcmQtbGluayIsICJraW5kIjogIlNlY3JldCIsICJkYXRhIjogeyJ1c2VySUQiOiAiY2VwaC1kYXNoYm9hcmQtbGluayIsICJ1c2VyS2V5IjogImh0dHBzOi8vMTAuNDYuMTg3Ljk5Ojg0NDMvIn19LCB7Im5hbWUiOiAiY2VwaGZzIiwgImtpbmQiOiAiU3RvcmFnZUNsYXNzIiwgImRhdGEiOiB7ImZzTmFtZSI6ICJ5cF9jZXBoZnMiLCAicG9vbCI6ICJjZXBoZnNfZGF0YSJ9fV0K
    - fileName: required/storage/odf-external/02-ocs-external-storagecluster.yaml
      policyName: "config-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "11"
    # storage classes from ODF
    # NOT PRESENT in CORE Container
    # - fileName: required/storage/odf-external/odf-sc-ceph-rbd.yaml
    #   policyName: "odf-storage-classes"
    # - fileName: required/storage/odf-external/odf-sc-ceph-fs.yaml
    #   policyName: "odf-storage-classes"
    # - fileName: required/storage/odf-external/odf-sc-nooba.yaml
    #   policyName: "odf-storage-classes"
    #   metadata:
    #     name: openshift-storage.noobaa.io
