---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "odf-storage-tlv2"
  namespace: "ztp-site"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    # install ODF operator
    - fileName: odf/ns.yaml
      policyName: "odf-operator"
    - fileName: odf/operatorGroup.yaml
      policyName: "odf-operator"
    - fileName: odf/subscription.yaml
      policyName: "odf-operator"
    # configure ODF operator
    - fileName: odf/external-ceph-secret.yaml
      policyName: "odf-operator-configure-1"
    - fileName: odf/odf-storage-cluster.yaml
      policyName: "odf-operator-configure-2"
    # storage classes from ODF
    - fileName: odf/odf-sc-ceph-rbd.yaml
      policyName: "odf-storage-classes"
    - fileName: odf/odf-sc-ceph-fs.yaml
      policyName: "odf-storage-classes"
    - fileName: odf/odf-sc-nooba.yaml
      policyName: "odf-storage-classes"
      metadata:
        name: openshift-storage.noobaa.io
