---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "odf-storage-tlv2"
  namespace: "ztp-site"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    # install ODF operator
    - fileName: required/storage/odf-external/odfNS.yaml
      policyName: "install-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "8"
    - fileName: required/storage/odf-external/odfOperGroup.yaml
      policyName: "install-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "8"
    - fileName: required/storage/odf-external/odfSubscription.yaml
      policyName: "install-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "8"
      spec:
        channel: "stable-4.16"
    # configure ODF operator
    - fileName: required/storage/odf-external/01-rook-ceph-external-cluster-details.secret.yaml
      policyName: "config-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "11"
      data:
        external_cluster_details: W3sibmFtZSI6ICJyb29rLWNlcGgtbW9uLWVuZHBvaW50cyIsICJraW5kIjogIkNvbmZpZ01hcCIsICJkYXRhIjogeyJkYXRhIjogImNlcGh1c2ExPTEwLjkuNzYuMTo2Nzg5IiwgIm1heE1vbklkIjogIjAiLCAibWFwcGluZyI6ICJ7fSJ9fSwgeyJuYW1lIjogInJvb2stY2VwaC1tb24iLCAia2luZCI6ICJTZWNyZXQiLCAiZGF0YSI6IHsiYWRtaW4tc2VjcmV0IjogImFkbWluLXNlY3JldCIsICJmc2lkIjogIjM4ZGQzODdlLTgzN2EtNDM3Yy04OTFjLTdmYzY5ZTE3YTJiYiIsICJtb24tc2VjcmV0IjogIm1vbi1zZWNyZXQifX0sIHsibmFtZSI6ICJyb29rLWNlcGgtb3BlcmF0b3ItY3JlZHMiLCAia2luZCI6ICJTZWNyZXQiLCAiZGF0YSI6IHsidXNlcklEIjogImNsaWVudC5oZWFsdGhjaGVja2VyIiwgInVzZXJLZXkiOiAiQVFDNVMySmtkZ1V5TXhBQXV0RmVJYmZvVTlXeHoxRVRGdjZmSWc9PSJ9fSwgeyJuYW1lIjogIm1vbml0b3JpbmctZW5kcG9pbnQiLCAia2luZCI6ICJDZXBoQ2x1c3RlciIsICJkYXRhIjogeyJNb25pdG9yaW5nRW5kcG9pbnQiOiAiMTAuOS43Ni4zLDEwLjkuNzYuMiwxMC45Ljc2LjEiLCAiTW9uaXRvcmluZ1BvcnQiOiAiOTI4MyJ9fSwgeyJuYW1lIjogImNlcGgtcmJkIiwgImtpbmQiOiAiU3RvcmFnZUNsYXNzIiwgImRhdGEiOiB7InBvb2wiOiAib2RmX3Bvb2wifX0sIHsibmFtZSI6ICJyb29rLWNzaS1yYmQtbm9kZSIsICJraW5kIjogIlNlY3JldCIsICJkYXRhIjogeyJ1c2VySUQiOiAiY3NpLXJiZC1ub2RlIiwgInVzZXJLZXkiOiAiQVFDNVMySmtsQjNwT0JBQVVOMnAvVnlSSnc0bU4wbXN5dlMxWlE9PSJ9fSwgeyJuYW1lIjogInJvb2stY3NpLXJiZC1wcm92aXNpb25lciIsICJraW5kIjogIlNlY3JldCIsICJkYXRhIjogeyJ1c2VySUQiOiAiY3NpLXJiZC1wcm92aXNpb25lciIsICJ1c2VyS2V5IjogIkFRQzZTMkprbVdXN0FSQUFXbnJCdU9EUlROdzVMTFNSUndqQW9BPT0ifX0sIHsibmFtZSI6ICJyb29rLWNzaS1jZXBoZnMtcHJvdmlzaW9uZXIiLCAia2luZCI6ICJTZWNyZXQiLCAiZGF0YSI6IHsiYWRtaW5JRCI6ICJjc2ktY2VwaGZzLXByb3Zpc2lvbmVyIiwgImFkbWluS2V5IjogIkFRQzZTMkprcGpTU0VCQUFabHV1YSt6WHEzMHVMV2krL0lOOEN3PT0ifX0sIHsibmFtZSI6ICJyb29rLWNzaS1jZXBoZnMtbm9kZSIsICJraW5kIjogIlNlY3JldCIsICJkYXRhIjogeyJhZG1pbklEIjogImNzaS1jZXBoZnMtbm9kZSIsICJhZG1pbktleSI6ICJBUUM2UzJKazgxcUpDQkFBYkJjMUhybzlqczQ2dGJvc3FxcEtZdz09In19LCB7Im5hbWUiOiAiY2VwaGZzIiwgImtpbmQiOiAiU3RvcmFnZUNsYXNzIiwgImRhdGEiOiB7ImZzTmFtZSI6ICJjZXBoZnMiLCAicG9vbCI6ICJtYW5pbGFfZGF0YSJ9fV0K
    - fileName: required/storage/odf-external/02-ocs-external-storagecluster.yaml
      policyName: "config-odf-operator"
      metadata:
        annotations:
          ran.openshift.io/ztp-deploy-wave: "11"
    # storage classes from ODF
    # NOT PRESENT in CORE Container
    # - fileName: required/storage/odf-external/odf-sc-ceph-rbd.yaml
    #   policyName: "odf-storage-classes"
    # - fileName: required/storage/odf-external/odf-sc-ceph-fs.yaml
    #   policyName: "odf-storage-classes"
    # - fileName: required/storage/odf-external/odf-sc-nooba.yaml
    #   policyName: "odf-storage-classes"
    #   metadata:
    #     name: openshift-storage.noobaa.io
