---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "label-workers-tlv2"
  namespace: "ztp-site"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    - fileName: LabelNode.yaml
      policyName: pcc-label
      metadata:
        name: openshift-worker-0.ecore.lab.eng.tlv2.redhat.com
        labels:
          acm-policy-labels-workaround: enabled
          rds-label-one: rds-core-one
          rds-label-two: rds-core-two
      spec: {}
    - fileName: LabelNode.yaml
      policyName: pcc-label
      metadata:
        name: openshift-worker-1.ecore.lab.eng.tlv2.redhat.com
        labels:
          acm-policy-labels-workaround: enabled
          rds-label-one: rds-core-one
          rds-label-two: rds-core-two
      spec: {}
    - fileName: LabelNode.yaml
      policyName: pcc-label
      metadata:
        name: openshift-worker-2.ecore.lab.eng.tlv2.redhat.com
        labels:
          node-role.kubernetes.io/customcnf: ""
          acm-policy-labels-workaround: enabled
          type: powerful
    - fileName: LabelNode.yaml
      policyName: pcc-label
      metadata:
        name: openshift-worker-3.ecore.lab.eng.tlv2.redhat.com
        labels:
          node-role.kubernetes.io/customcnf: ""
          acm-policy-labels-workaround: enabled
          type: powerful
