---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "label-workers-tlv2"
  namespace: "ztp-site"
spec:
  bindingRules:
    site: "ecore"
    zone: "tlv2"
  remediationAction: inform
  sourceFiles:
    - fileName: LabelHTNode.yaml
      policyName: "taint-node"
      metadata:
        name: openshift-worker-2.ecore.lab.eng.tlv2.redhat.com
      spec:
        taints:
          - effect: NoSchedule
            key: sriov
            value: "true"
    - fileName: LabelHTNode.yaml
      policyName: "taint-node"
      metadata:
        name: openshift-worker-3.ecore.lab.eng.tlv2.redhat.com
      spec:
        taints:
          - effect: NoSchedule
            key: sriov
            value: "true"
