apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pre-req/
- ecore.yaml

configMapGenerator:
  - files:
    - mno-extra-manifests/00-debug-networkmanager-master.yaml
    - mno-extra-manifests/00-debug-networkmanager-worker.yaml
    - mno-extra-manifests/05-disconnected-idms.yaml
    - mno-extra-manifests/kdump-master.yaml
    - mno-extra-manifests/kdump-worker.yaml
    - mno-extra-manifests/98-master-etc-chrony-conf.yaml
    - mno-extra-manifests/98-worker-etc-chrony-conf.yaml
    - mno-extra-manifests/control-plane-load-kernel-modules.yaml
    - mno-extra-manifests/mc_rootless_pods_selinux.yaml
    - mno-extra-manifests/mount_namespace_config_master.yaml
    - mno-extra-manifests/mount_namespace_config_worker.yaml
    - mno-extra-manifests/sctp_module_mc.yaml
    - mno-extra-manifests/worker-load-kernel-modules.yaml
    - mno-extra-manifests/configure-core-pass-compute.yaml
    - mno-extra-manifests/configure-core-pass-cp.yaml
    - mno-extra-manifests/Network.yaml
    name: extra-manifests-cm
    namespace: ecore
  - files:
    - custom-manifests/50-mcp-customcnf.yaml
    - custom-manifests/50-mcp-st.yaml
    name: custom-manifests-cm
    namespace: ecore
generatorOptions:
  disableNameSuffixHash: true
